/**
  * \file VecPlnrVCall.h
  * vector VecPlnrVCall (declarations)
  * \author Alexander Wirthmueller
  * \date created: 4 Dec 2015
  * \date modified: 4 Dec 2015
  */

#ifndef VECPLNRVCALL_H
#define VECPLNRVCALL_H

#include <dartcore/Xmlio.h>

using namespace Xmlio;

/**
	* VecPlnrVCall
	*/
namespace VecPlnrVCall {
	const uint CALLPLNRACCESS = 1;
	const uint CALLPLNRAGDJRMOD_AGDEQ = 2;
	const uint CALLPLNRAGDMOD = 3;
	const uint CALLPLNRAGDMOD_DAGEQ = 4;
	const uint CALLPLNRAGDMOD_HKTHKUEQ = 5;
	const uint CALLPLNRAGDRVTXMOD_AGDEQ = 6;
	const uint CALLPLNRAGDRVTXMOD_VTXEQ = 7;
	const uint CALLPLNRAGDUPD_REFEQ = 8;
	const uint CALLPLNRARIMOD = 9;
	const uint CALLPLNRARIMOD_ARREQ = 10;
	const uint CALLPLNRARIUPD_REFEQ = 11;
	const uint CALLPLNRARRAENVMOD_ARREQ = 12;
	const uint CALLPLNRARRMOD = 13;
	const uint CALLPLNRARRMOD_TPOEQ = 14;
	const uint CALLPLNRARRUPD_REFEQ = 15;
	const uint CALLPLNRBLKMOD = 16;
	const uint CALLPLNRBLKMOD_DSNEQ = 17;
	const uint CALLPLNRBLKMOD_LYREQ = 18;
	const uint CALLPLNRBLKMOD_SRUEQ = 19;
	const uint CALLPLNRBLKUPD_REFEQ = 20;
	const uint CALLPLNRBOOLVALPRESET = 21;
	const uint CALLPLNRCALAENVMOD_CALEQ = 22;
	const uint CALLPLNRCALAPARMOD_CALEQ = 23;
	const uint CALLPLNRCALMOD = 24;
	const uint CALLPLNRCALMOD_PRJEQ = 25;
	const uint CALLPLNRCALMOD_SUPEQ = 26;
	const uint CALLPLNRCALMOD_TPLEQ = 27;
	const uint CALLPLNRCALRDOMMOD_CALEQ = 28;
	const uint CALLPLNRCALRDOMMOD_DOMEQ = 29;
	const uint CALLPLNRCALRFILMOD_CALEQ = 30;
	const uint CALLPLNRCALRFILMOD_FILEQ = 31;
	const uint CALLPLNRCALUPD_REFEQ = 32;
	const uint CALLPLNRCLIMOD = 33;
	const uint CALLPLNRCLIMOD_CALEQ = 34;
	const uint CALLPLNRCLIUPD_REFEQ = 35;
	const uint CALLPLNRCNTAPARMOD_USREQ = 36;
	const uint CALLPLNRCRDACTIVE = 37;
	const uint CALLPLNRCRDCLOSE = 38;
	const uint CALLPLNRCRDOPEN = 39;
	const uint CALLPLNRDBLVALPRESET = 40;
	const uint CALLPLNRDEVAPARMOD_DEVEQ = 41;
	const uint CALLPLNRDEVAPARMOD_DSNEQ = 42;
	const uint CALLPLNRDEVJMODMOD_DEVEQ = 43;
	const uint CALLPLNRDEVMOD = 44;
	const uint CALLPLNRDEVMOD_DSNEQ = 45;
	const uint CALLPLNRDEVMOD_SUPEQ = 46;
	const uint CALLPLNRDEVMOD_TPLEQ = 47;
	const uint CALLPLNRDEVUPD_REFEQ = 48;
	const uint CALLPLNRDGDJMOD_DGDEQ = 49;
	const uint CALLPLNRDGDMOD = 50;
	const uint CALLPLNRDGDMOD_DSNEQ = 51;
	const uint CALLPLNRDGDUPD_REFEQ = 52;
	const uint CALLPLNRDLGCLOSE = 53;
	const uint CALLPLNRDOMJMOD_DOMEQ = 54;
	const uint CALLPLNRDOMMOD = 55;
	const uint CALLPLNRDOMMOD_DSNEQ = 56;
	const uint CALLPLNRDOMUPD_REFEQ = 57;
	const uint CALLPLNRDSN_DIMEQ = 58;
	const uint CALLPLNRDSN_MODEQ = 59;
	const uint CALLPLNRDSN_TYPEQ = 60;
	const uint CALLPLNRDSNMOD = 61;
	const uint CALLPLNRDSNMOD_DRVEQ = 62;
	const uint CALLPLNRDSNMOD_MODEQ = 63;
	const uint CALLPLNRDSNMOD_PRJEQ = 64;
	const uint CALLPLNRDSNMOD_RETREUEQ = 65;
	const uint CALLPLNRDSNUPD_REFEQ = 66;
	const uint CALLPLNRFCEMOD = 67;
	const uint CALLPLNRFCEMOD_DFCEQ = 68;
	const uint CALLPLNRFCEMOD_SRUEQ = 69;
	const uint CALLPLNRFCERVTXMOD_FCEEQ = 70;
	const uint CALLPLNRFCERVTXMOD_VTXEQ = 71;
	const uint CALLPLNRFCEUPD_REFEQ = 72;
	const uint CALLPLNRFIL_CLUEQ = 73;
	const uint CALLPLNRFILMOD = 74;
	const uint CALLPLNRFILMOD_CLUEQ = 75;
	const uint CALLPLNRFILMOD_RETREUEQ = 76;
	const uint CALLPLNRFILUPD_REFEQ = 77;
	const uint CALLPLNRHUSRRUNVMOD_CRDUSREQ = 78;
	const uint CALLPLNRINTVALPRESET = 79;
	const uint CALLPLNRIXPRESET = 80;
	const uint CALLPLNRKLKJKEYMOD_KLSAKEYEQ = 81;
	const uint CALLPLNRKLSAKEYMOD_KLSEQ = 82;
	const uint CALLPLNRKLSAKEYMOD_KLSMTBURFEQ = 83;
	const uint CALLPLNRLGDMOD = 84;
	const uint CALLPLNRLGDMOD_HKTHKUEQ = 85;
	const uint CALLPLNRLGDRLGDMOD_DSLEQ = 86;
	const uint CALLPLNRLGDRLGDMOD_DVLEQ = 87;
	const uint CALLPLNRLGDRVTXMOD_LGDEQ = 88;
	const uint CALLPLNRLGDRVTXMOD_VTXEQ = 89;
	const uint CALLPLNRLGDUPD_REFEQ = 90;
	const uint CALLPLNRLOG = 91;
	const uint CALLPLNRLOGOUT = 92;
	const uint CALLPLNRLVLJZMOD_LVLEQ = 93;
	const uint CALLPLNRLVLMOD = 94;
	const uint CALLPLNRLVLMOD_HKTHKUEQ = 95;
	const uint CALLPLNRLVLRLVLMOD_DLVEQ = 96;
	const uint CALLPLNRLVLRLVLMOD_SLVEQ = 97;
	const uint CALLPLNRLVLUPD_REFEQ = 98;
	const uint CALLPLNRLYRJMATMOD_LYREQ = 99;
	const uint CALLPLNRLYRJMOD_LYREQ = 100;
	const uint CALLPLNRLYRMOD = 101;
	const uint CALLPLNRLYRMOD_HKTHKUEQ = 102;
	const uint CALLPLNRLYRMOD_MATEQ = 103;
	const uint CALLPLNRLYRRSRUMOD_LYREQ = 104;
	const uint CALLPLNRLYRRSRUMOD_SRUEQ = 105;
	const uint CALLPLNRLYRUPD_REFEQ = 106;
	const uint CALLPLNRMASTCLAIM = 107;
	const uint CALLPLNRMASTSLVCHG = 108;
	const uint CALLPLNRMATAPARMOD_DSNEQ = 109;
	const uint CALLPLNRMATAPARMOD_MATEQ = 110;
	const uint CALLPLNRMATMOD = 111;
	const uint CALLPLNRMATMOD_CALEQ = 112;
	const uint CALLPLNRMATMOD_SUPEQ = 113;
	const uint CALLPLNRMATUPD_REFEQ = 114;
	const uint CALLPLNRPRJJSTEMOD_PRJEQ = 115;
	const uint CALLPLNRPRJMOD = 116;
	const uint CALLPLNRPRJRTPOMOD_PRJEQ = 117;
	const uint CALLPLNRPRJRTPOMOD_TPOEQ = 118;
	const uint CALLPLNRPRJUPD_REFEQ = 119;
	const uint CALLPLNRPRSADETMOD_PRSEQ = 120;
	const uint CALLPLNRPRSJLNMMOD_PRSEQ = 121;
	const uint CALLPLNRPRSMOD = 122;
	const uint CALLPLNRPRSUPD_REFEQ = 123;
	const uint CALLPLNRREFPRESET = 124;
	const uint CALLPLNRREFSPRESET = 125;
	const uint CALLPLNRRTCMOD = 126;
	const uint CALLPLNRRTCMOD_DSNEQ = 127;
	const uint CALLPLNRRTCMOD_HKTHKUEQ = 128;
	const uint CALLPLNRRTCMOD_LYREQ = 129;
	const uint CALLPLNRRTCUPD_REFEQ = 130;
	const uint CALLPLNRSESMOD = 131;
	const uint CALLPLNRSESMOD_USREQ = 132;
	const uint CALLPLNRSESUPD_REFEQ = 133;
	const uint CALLPLNRSREFPRESET = 134;
	const uint CALLPLNRSRUMOD = 135;
	const uint CALLPLNRSRUMOD_HKTHKUEQ = 136;
	const uint CALLPLNRSRUUPD_REFEQ = 137;
	const uint CALLPLNRSTATCHG = 138;
	const uint CALLPLNRSTGCHG = 139;
	const uint CALLPLNRSTKJMODMOD_STKEQ = 140;
	const uint CALLPLNRSTKJNMOD_STKEQ = 141;
	const uint CALLPLNRSTKMOD = 142;
	const uint CALLPLNRSTKMOD_DSNEQ = 143;
	const uint CALLPLNRSTKRSRUMOD_SRUEQ = 144;
	const uint CALLPLNRSTKRSRUMOD_STKEQ = 145;
	const uint CALLPLNRSTKUPD_REFEQ = 146;
	const uint CALLPLNRSTUBCHG = 147;
	const uint CALLPLNRTPOJSTEMOD_TPOEQ = 148;
	const uint CALLPLNRTPOMOD = 149;
	const uint CALLPLNRTPOUPD_REFEQ = 150;
	const uint CALLPLNRTXTVALPRESET = 151;
	const uint CALLPLNRUSGAACCMOD_USGEQ = 152;
	const uint CALLPLNRUSGMOD = 153;
	const uint CALLPLNRUSGUPD_REFEQ = 154;
	const uint CALLPLNRUSRAACCMOD_USREQ = 155;
	const uint CALLPLNRUSRJSTEMOD_USREQ = 156;
	const uint CALLPLNRUSRMOD = 157;
	const uint CALLPLNRUSRRUSGMOD_USGEQ = 158;
	const uint CALLPLNRUSRRUSGMOD_USREQ = 159;
	const uint CALLPLNRUSRUPD_REFEQ = 160;
	const uint CALLPLNRVTXJMOD_VTXEQ = 161;
	const uint CALLPLNRVTXMOD = 162;
	const uint CALLPLNRVTXMOD_HKTHKUEQ = 163;
	const uint CALLPLNRVTXRVTXMOD_DSVEQ = 164;
	const uint CALLPLNRVTXRVTXMOD_DVVEQ = 165;
	const uint CALLPLNRVTXUPD_REFEQ = 166;

	uint getIx(const string& sref);
	string getSref(const uint ix);
};

#endif


