/**
  * \file VecPlnrVDpch.cpp
  * vector VecPlnrVDpch (implementation)
  * \author Alexander Wirthmueller
  * \date created: 4 Dec 2015
  * \date modified: 4 Dec 2015
  */

#include "VecPlnrVDpch.h"

/******************************************************************************
 namespace VecPlnrVDpch
 ******************************************************************************/

uint VecPlnrVDpch::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "dpchappdlgplnrclcexprtxdo") return DPCHAPPDLGPLNRCLCEXPRTXDO;
	else if (s == "dpchappdlgplnrclcgenrpvdo") return DPCHAPPDLGPLNRCLCGENRPVDO;
	else if (s == "dpchappdlgplnrclcusecasedata") return DPCHAPPDLGPLNRCLCUSECASEDATA;
	else if (s == "dpchappdlgplnrclcusecasedo") return DPCHAPPDLGPLNRCLCUSECASEDO;
	else if (s == "dpchappdlgplnrdsngenpltdo") return DPCHAPPDLGPLNRDSNGENPLTDO;
	else if (s == "dpchappdlgplnrfildldcpydo") return DPCHAPPDLGPLNRFILDLDCPYDO;
	else if (s == "dpchappdlgplnrnavloainidata") return DPCHAPPDLGPLNRNAVLOAINIDATA;
	else if (s == "dpchappdlgplnrnavloainido") return DPCHAPPDLGPLNRNAVLOAINIDO;
	else if (s == "dpchappdlgplnrtpousecasedata") return DPCHAPPDLGPLNRTPOUSECASEDATA;
	else if (s == "dpchappdlgplnrtpousecasedo") return DPCHAPPDLGPLNRTPOUSECASEDO;
	else if (s == "dpchappplnralert") return DPCHAPPPLNRALERT;
	else if (s == "dpchappplnrariamarrayenvdata") return DPCHAPPPLNRARIAMARRAYENVDATA;
	else if (s == "dpchappplnrariamarrayenvdo") return DPCHAPPPLNRARIAMARRAYENVDO;
	else if (s == "dpchappplnraridetaildata") return DPCHAPPPLNRARIDETAILDATA;
	else if (s == "dpchappplnraridetaildo") return DPCHAPPPLNRARIDETAILDO;
	else if (s == "dpchappplnrarido") return DPCHAPPPLNRARIDO;
	else if (s == "dpchappplnrarilistdata") return DPCHAPPPLNRARILISTDATA;
	else if (s == "dpchappplnrarilistdo") return DPCHAPPPLNRARILISTDO;
	else if (s == "dpchappplnrarirecdo") return DPCHAPPPLNRARIRECDO;
	else if (s == "dpchappplnrarr1narrayitemdata") return DPCHAPPPLNRARR1NARRAYITEMDATA;
	else if (s == "dpchappplnrarr1narrayitemdo") return DPCHAPPPLNRARR1NARRAYITEMDO;
	else if (s == "dpchappplnrarraenvdata") return DPCHAPPPLNRARRAENVDATA;
	else if (s == "dpchappplnrarraenvdo") return DPCHAPPPLNRARRAENVDO;
	else if (s == "dpchappplnrarrdetaildata") return DPCHAPPPLNRARRDETAILDATA;
	else if (s == "dpchappplnrarrdetaildo") return DPCHAPPPLNRARRDETAILDO;
	else if (s == "dpchappplnrarrdo") return DPCHAPPPLNRARRDO;
	else if (s == "dpchappplnrarrhk1nreticledata") return DPCHAPPPLNRARRHK1NRETICLEDATA;
	else if (s == "dpchappplnrarrhk1nreticledo") return DPCHAPPPLNRARRHK1NRETICLEDO;
	else if (s == "dpchappplnrarrkenvkeydata") return DPCHAPPPLNRARRKENVKEYDATA;
	else if (s == "dpchappplnrarrkenvkeydo") return DPCHAPPPLNRARRKENVKEYDO;
	else if (s == "dpchappplnrarrlistdata") return DPCHAPPPLNRARRLISTDATA;
	else if (s == "dpchappplnrarrlistdo") return DPCHAPPPLNRARRLISTDO;
	else if (s == "dpchappplnrarrrecdo") return DPCHAPPPLNRARRRECDO;
	else if (s == "dpchappplnrclc1nmaterialdata") return DPCHAPPPLNRCLC1NMATERIALDATA;
	else if (s == "dpchappplnrclc1nmaterialdo") return DPCHAPPPLNRCLC1NMATERIALDO;
	else if (s == "dpchappplnrclcaenvdata") return DPCHAPPPLNRCLCAENVDATA;
	else if (s == "dpchappplnrclcaenvdo") return DPCHAPPPLNRCLCAENVDO;
	else if (s == "dpchappplnrclcapardata") return DPCHAPPPLNRCLCAPARDATA;
	else if (s == "dpchappplnrclcapardo") return DPCHAPPPLNRCLCAPARDO;
	else if (s == "dpchappplnrclccal1ncalcitemdata") return DPCHAPPPLNRCLCCAL1NCALCITEMDATA;
	else if (s == "dpchappplnrclccal1ncalcitemdo") return DPCHAPPPLNRCLCCAL1NCALCITEMDO;
	else if (s == "dpchappplnrclcdetaildata") return DPCHAPPPLNRCLCDETAILDATA;
	else if (s == "dpchappplnrclcdetaildo") return DPCHAPPPLNRCLCDETAILDO;
	else if (s == "dpchappplnrclcdo") return DPCHAPPPLNRCLCDO;
	else if (s == "dpchappplnrclclistdata") return DPCHAPPPLNRCLCLISTDATA;
	else if (s == "dpchappplnrclclistdo") return DPCHAPPPLNRCLCLISTDO;
	else if (s == "dpchappplnrclcmndomaindata") return DPCHAPPPLNRCLCMNDOMAINDATA;
	else if (s == "dpchappplnrclcmndomaindo") return DPCHAPPPLNRCLCMNDOMAINDO;
	else if (s == "dpchappplnrclcmnfiledata") return DPCHAPPPLNRCLCMNFILEDATA;
	else if (s == "dpchappplnrclcmnfiledo") return DPCHAPPPLNRCLCMNFILEDO;
	else if (s == "dpchappplnrclcrecdo") return DPCHAPPPLNRCLCRECDO;
	else if (s == "dpchappplnrclcref1nfiledata") return DPCHAPPPLNRCLCREF1NFILEDATA;
	else if (s == "dpchappplnrclcref1nfiledo") return DPCHAPPPLNRCLCREF1NFILEDO;
	else if (s == "dpchappplnrclcsup1ncalcdata") return DPCHAPPPLNRCLCSUP1NCALCDATA;
	else if (s == "dpchappplnrclcsup1ncalcdo") return DPCHAPPPLNRCLCSUP1NCALCDO;
	else if (s == "dpchappplnrcliaamcalcenvdata") return DPCHAPPPLNRCLIAAMCALCENVDATA;
	else if (s == "dpchappplnrcliaamcalcenvdo") return DPCHAPPPLNRCLIAAMCALCENVDO;
	else if (s == "dpchappplnrcliaamcalcpardata") return DPCHAPPPLNRCLIAAMCALCPARDATA;
	else if (s == "dpchappplnrcliaamcalcpardo") return DPCHAPPPLNRCLIAAMCALCPARDO;
	else if (s == "dpchappplnrclidetaildata") return DPCHAPPPLNRCLIDETAILDATA;
	else if (s == "dpchappplnrclidetaildo") return DPCHAPPPLNRCLIDETAILDO;
	else if (s == "dpchappplnrclido") return DPCHAPPPLNRCLIDO;
	else if (s == "dpchappplnrclilistdata") return DPCHAPPPLNRCLILISTDATA;
	else if (s == "dpchappplnrclilistdo") return DPCHAPPPLNRCLILISTDO;
	else if (s == "dpchappplnrclirecdo") return DPCHAPPPLNRCLIRECDO;
	else if (s == "dpchappplnrcliref1nfiledata") return DPCHAPPPLNRCLIREF1NFILEDATA;
	else if (s == "dpchappplnrcliref1nfiledo") return DPCHAPPPLNRCLIREF1NFILEDO;
	else if (s == "dpchappplnrctpaenvdata") return DPCHAPPPLNRCTPAENVDATA;
	else if (s == "dpchappplnrctpaenvdo") return DPCHAPPPLNRCTPAENVDO;
	else if (s == "dpchappplnrctpapardata") return DPCHAPPPLNRCTPAPARDATA;
	else if (s == "dpchappplnrctpapardo") return DPCHAPPPLNRCTPAPARDO;
	else if (s == "dpchappplnrctpdetaildata") return DPCHAPPPLNRCTPDETAILDATA;
	else if (s == "dpchappplnrctpdetaildo") return DPCHAPPPLNRCTPDETAILDO;
	else if (s == "dpchappplnrctpdo") return DPCHAPPPLNRCTPDO;
	else if (s == "dpchappplnrctpkcalcdomprpdata") return DPCHAPPPLNRCTPKCALCDOMPRPDATA;
	else if (s == "dpchappplnrctpkcalcdomprpdo") return DPCHAPPPLNRCTPKCALCDOMPRPDO;
	else if (s == "dpchappplnrctpkcalcvardata") return DPCHAPPPLNRCTPKCALCVARDATA;
	else if (s == "dpchappplnrctpkcalcvardo") return DPCHAPPPLNRCTPKCALCVARDO;
	else if (s == "dpchappplnrctpkenvkeydata") return DPCHAPPPLNRCTPKENVKEYDATA;
	else if (s == "dpchappplnrctpkenvkeydo") return DPCHAPPPLNRCTPKENVKEYDO;
	else if (s == "dpchappplnrctpkparcatdata") return DPCHAPPPLNRCTPKPARCATDATA;
	else if (s == "dpchappplnrctpkparcatdo") return DPCHAPPPLNRCTPKPARCATDO;
	else if (s == "dpchappplnrctpkparpropdata") return DPCHAPPPLNRCTPKPARPROPDATA;
	else if (s == "dpchappplnrctpkparpropdo") return DPCHAPPPLNRCTPKPARPROPDO;
	else if (s == "dpchappplnrctplistdata") return DPCHAPPPLNRCTPLISTDATA;
	else if (s == "dpchappplnrctplistdo") return DPCHAPPPLNRCTPLISTDO;
	else if (s == "dpchappplnrctprecdo") return DPCHAPPPLNRCTPRECDO;
	else if (s == "dpchappplnrctpref1nfiledata") return DPCHAPPPLNRCTPREF1NFILEDATA;
	else if (s == "dpchappplnrctpref1nfiledo") return DPCHAPPPLNRCTPREF1NFILEDO;
	else if (s == "dpchappplnrctpsup1ncalcdata") return DPCHAPPPLNRCTPSUP1NCALCDATA;
	else if (s == "dpchappplnrctpsup1ncalcdo") return DPCHAPPPLNRCTPSUP1NCALCDO;
	else if (s == "dpchappplnrctptpl1ncalcdata") return DPCHAPPPLNRCTPTPL1NCALCDATA;
	else if (s == "dpchappplnrctptpl1ncalcdo") return DPCHAPPPLNRCTPTPL1NCALCDO;
	else if (s == "dpchappplnrdgddetaildata") return DPCHAPPPLNRDGDDETAILDATA;
	else if (s == "dpchappplnrdgddetaildo") return DPCHAPPPLNRDGDDETAILDO;
	else if (s == "dpchappplnrdgddo") return DPCHAPPPLNRDGDDO;
	else if (s == "dpchappplnrdgdlistdata") return DPCHAPPPLNRDGDLISTDATA;
	else if (s == "dpchappplnrdgdlistdo") return DPCHAPPPLNRDGDLISTDO;
	else if (s == "dpchappplnrdgdrecdo") return DPCHAPPPLNRDGDRECDO;
	else if (s == "dpchappplnrdomdetaildata") return DPCHAPPPLNRDOMDETAILDATA;
	else if (s == "dpchappplnrdomdetaildo") return DPCHAPPPLNRDOMDETAILDO;
	else if (s == "dpchappplnrdomdo") return DPCHAPPPLNRDOMDO;
	else if (s == "dpchappplnrdomlistdata") return DPCHAPPPLNRDOMLISTDATA;
	else if (s == "dpchappplnrdomlistdo") return DPCHAPPPLNRDOMLISTDO;
	else if (s == "dpchappplnrdommncalcdata") return DPCHAPPPLNRDOMMNCALCDATA;
	else if (s == "dpchappplnrdommncalcdo") return DPCHAPPPLNRDOMMNCALCDO;
	else if (s == "dpchappplnrdomrecdo") return DPCHAPPPLNRDOMRECDO;
	else if (s == "dpchappplnrdsn1nblockdata") return DPCHAPPPLNRDSN1NBLOCKDATA;
	else if (s == "dpchappplnrdsn1nblockdo") return DPCHAPPPLNRDSN1NBLOCKDO;
	else if (s == "dpchappplnrdsn1nreticledata") return DPCHAPPPLNRDSN1NRETICLEDATA;
	else if (s == "dpchappplnrdsn1nreticledo") return DPCHAPPPLNRDSN1NRETICLEDO;
	else if (s == "dpchappplnrdsndetaildata") return DPCHAPPPLNRDSNDETAILDATA;
	else if (s == "dpchappplnrdsndetaildo") return DPCHAPPPLNRDSNDETAILDO;
	else if (s == "dpchappplnrdsndo") return DPCHAPPPLNRDSNDO;
	else if (s == "dpchappplnrdsndrv1ndesigndata") return DPCHAPPPLNRDSNDRV1NDESIGNDATA;
	else if (s == "dpchappplnrdsndrv1ndesigndo") return DPCHAPPPLNRDSNDRV1NDESIGNDO;
	else if (s == "dpchappplnrdsndsn1ndevicedata") return DPCHAPPPLNRDSNDSN1NDEVICEDATA;
	else if (s == "dpchappplnrdsndsn1ndevicedo") return DPCHAPPPLNRDSNDSN1NDEVICEDO;
	else if (s == "dpchappplnrdsndsn1ndomaindata") return DPCHAPPPLNRDSNDSN1NDOMAINDATA;
	else if (s == "dpchappplnrdsndsn1ndomaindo") return DPCHAPPPLNRDSNDSN1NDOMAINDO;
	else if (s == "dpchappplnrdsndsn1ndomaingddata") return DPCHAPPPLNRDSNDSN1NDOMAINGDDATA;
	else if (s == "dpchappplnrdsndsn1ndomaingddo") return DPCHAPPPLNRDSNDSN1NDOMAINGDDO;
	else if (s == "dpchappplnrdsndsn1nstackdata") return DPCHAPPPLNRDSNDSN1NSTACKDATA;
	else if (s == "dpchappplnrdsndsn1nstackdo") return DPCHAPPPLNRDSNDSN1NSTACKDO;
	else if (s == "dpchappplnrdsnhk1narcguidedata") return DPCHAPPPLNRDSNHK1NARCGUIDEDATA;
	else if (s == "dpchappplnrdsnhk1narcguidedo") return DPCHAPPPLNRDSNHK1NARCGUIDEDO;
	else if (s == "dpchappplnrdsnhk1nlayerdata") return DPCHAPPPLNRDSNHK1NLAYERDATA;
	else if (s == "dpchappplnrdsnhk1nlayerdo") return DPCHAPPPLNRDSNHK1NLAYERDO;
	else if (s == "dpchappplnrdsnhk1nleveldata") return DPCHAPPPLNRDSNHK1NLEVELDATA;
	else if (s == "dpchappplnrdsnhk1nleveldo") return DPCHAPPPLNRDSNHK1NLEVELDO;
	else if (s == "dpchappplnrdsnhk1nlineguidedata") return DPCHAPPPLNRDSNHK1NLINEGUIDEDATA;
	else if (s == "dpchappplnrdsnhk1nlineguidedo") return DPCHAPPPLNRDSNHK1NLINEGUIDEDO;
	else if (s == "dpchappplnrdsnhk1nstructuredata") return DPCHAPPPLNRDSNHK1NSTRUCTUREDATA;
	else if (s == "dpchappplnrdsnhk1nstructuredo") return DPCHAPPPLNRDSNHK1NSTRUCTUREDO;
	else if (s == "dpchappplnrdsnhk1nvertexdata") return DPCHAPPPLNRDSNHK1NVERTEXDATA;
	else if (s == "dpchappplnrdsnhk1nvertexdo") return DPCHAPPPLNRDSNHK1NVERTEXDO;
	else if (s == "dpchappplnrdsnlistdata") return DPCHAPPPLNRDSNLISTDATA;
	else if (s == "dpchappplnrdsnlistdo") return DPCHAPPPLNRDSNLISTDO;
	else if (s == "dpchappplnrdsnmod1ndesigndata") return DPCHAPPPLNRDSNMOD1NDESIGNDATA;
	else if (s == "dpchappplnrdsnmod1ndesigndo") return DPCHAPPPLNRDSNMOD1NDESIGNDO;
	else if (s == "dpchappplnrdsnrecdo") return DPCHAPPPLNRDSNRECDO;
	else if (s == "dpchappplnrdtpapardata") return DPCHAPPPLNRDTPAPARDATA;
	else if (s == "dpchappplnrdtpapardo") return DPCHAPPPLNRDTPAPARDO;
	else if (s == "dpchappplnrdtpdetaildata") return DPCHAPPPLNRDTPDETAILDATA;
	else if (s == "dpchappplnrdtpdetaildo") return DPCHAPPPLNRDTPDETAILDO;
	else if (s == "dpchappplnrdtpdo") return DPCHAPPPLNRDTPDO;
	else if (s == "dpchappplnrdtphk1nstructuredata") return DPCHAPPPLNRDTPHK1NSTRUCTUREDATA;
	else if (s == "dpchappplnrdtphk1nstructuredo") return DPCHAPPPLNRDTPHK1NSTRUCTUREDO;
	else if (s == "dpchappplnrdtpkparkeydata") return DPCHAPPPLNRDTPKPARKEYDATA;
	else if (s == "dpchappplnrdtpkparkeydo") return DPCHAPPPLNRDTPKPARKEYDO;
	else if (s == "dpchappplnrdtplistdata") return DPCHAPPPLNRDTPLISTDATA;
	else if (s == "dpchappplnrdtplistdo") return DPCHAPPPLNRDTPLISTDO;
	else if (s == "dpchappplnrdtprecdo") return DPCHAPPPLNRDTPRECDO;
	else if (s == "dpchappplnrdtpsup1ndevicedata") return DPCHAPPPLNRDTPSUP1NDEVICEDATA;
	else if (s == "dpchappplnrdtpsup1ndevicedo") return DPCHAPPPLNRDTPSUP1NDEVICEDO;
	else if (s == "dpchappplnrdtptpl1ndevicedata") return DPCHAPPPLNRDTPTPL1NDEVICEDATA;
	else if (s == "dpchappplnrdtptpl1ndevicedo") return DPCHAPPPLNRDTPTPL1NDEVICEDO;
	else if (s == "dpchappplnrdvcapardata") return DPCHAPPPLNRDVCAPARDATA;
	else if (s == "dpchappplnrdvcapardo") return DPCHAPPPLNRDVCAPARDO;
	else if (s == "dpchappplnrdvcdetaildata") return DPCHAPPPLNRDVCDETAILDATA;
	else if (s == "dpchappplnrdvcdetaildo") return DPCHAPPPLNRDVCDETAILDO;
	else if (s == "dpchappplnrdvcdo") return DPCHAPPPLNRDVCDO;
	else if (s == "dpchappplnrdvchk1narcguidedata") return DPCHAPPPLNRDVCHK1NARCGUIDEDATA;
	else if (s == "dpchappplnrdvchk1narcguidedo") return DPCHAPPPLNRDVCHK1NARCGUIDEDO;
	else if (s == "dpchappplnrdvchk1nlineguidedata") return DPCHAPPPLNRDVCHK1NLINEGUIDEDATA;
	else if (s == "dpchappplnrdvchk1nlineguidedo") return DPCHAPPPLNRDVCHK1NLINEGUIDEDO;
	else if (s == "dpchappplnrdvchk1nstructuredata") return DPCHAPPPLNRDVCHK1NSTRUCTUREDATA;
	else if (s == "dpchappplnrdvchk1nstructuredo") return DPCHAPPPLNRDVCHK1NSTRUCTUREDO;
	else if (s == "dpchappplnrdvchk1nvertexdata") return DPCHAPPPLNRDVCHK1NVERTEXDATA;
	else if (s == "dpchappplnrdvchk1nvertexdo") return DPCHAPPPLNRDVCHK1NVERTEXDO;
	else if (s == "dpchappplnrdvclistdata") return DPCHAPPPLNRDVCLISTDATA;
	else if (s == "dpchappplnrdvclistdo") return DPCHAPPPLNRDVCLISTDO;
	else if (s == "dpchappplnrdvcrecdo") return DPCHAPPPLNRDVCRECDO;
	else if (s == "dpchappplnrdvcsup1ndevicedata") return DPCHAPPPLNRDVCSUP1NDEVICEDATA;
	else if (s == "dpchappplnrdvcsup1ndevicedo") return DPCHAPPPLNRDVCSUP1NDEVICEDO;
	else if (s == "dpchappplnrfildetaildata") return DPCHAPPPLNRFILDETAILDATA;
	else if (s == "dpchappplnrfildetaildo") return DPCHAPPPLNRFILDETAILDO;
	else if (s == "dpchappplnrfildo") return DPCHAPPPLNRFILDO;
	else if (s == "dpchappplnrfillistdata") return DPCHAPPPLNRFILLISTDATA;
	else if (s == "dpchappplnrfillistdo") return DPCHAPPPLNRFILLISTDO;
	else if (s == "dpchappplnrfilmncalcdata") return DPCHAPPPLNRFILMNCALCDATA;
	else if (s == "dpchappplnrfilmncalcdo") return DPCHAPPPLNRFILMNCALCDO;
	else if (s == "dpchappplnrfilrecdo") return DPCHAPPPLNRFILRECDO;
	else if (s == "dpchappplnrinit") return DPCHAPPPLNRINIT;
	else if (s == "dpchappplnrlyr1nblockdata") return DPCHAPPPLNRLYR1NBLOCKDATA;
	else if (s == "dpchappplnrlyr1nblockdo") return DPCHAPPPLNRLYR1NBLOCKDO;
	else if (s == "dpchappplnrlyr1nreticledata") return DPCHAPPPLNRLYR1NRETICLEDATA;
	else if (s == "dpchappplnrlyr1nreticledo") return DPCHAPPPLNRLYR1NRETICLEDO;
	else if (s == "dpchappplnrlyrdetaildata") return DPCHAPPPLNRLYRDETAILDATA;
	else if (s == "dpchappplnrlyrdetaildo") return DPCHAPPPLNRLYRDETAILDO;
	else if (s == "dpchappplnrlyrdo") return DPCHAPPPLNRLYRDO;
	else if (s == "dpchappplnrlyrlistdata") return DPCHAPPPLNRLYRLISTDATA;
	else if (s == "dpchappplnrlyrlistdo") return DPCHAPPPLNRLYRLISTDO;
	else if (s == "dpchappplnrlyrmnstructuredata") return DPCHAPPPLNRLYRMNSTRUCTUREDATA;
	else if (s == "dpchappplnrlyrmnstructuredo") return DPCHAPPPLNRLYRMNSTRUCTUREDO;
	else if (s == "dpchappplnrlyrrecdo") return DPCHAPPPLNRLYRRECDO;
	else if (s == "dpchappplnrmat1nlayerdata") return DPCHAPPPLNRMAT1NLAYERDATA;
	else if (s == "dpchappplnrmat1nlayerdo") return DPCHAPPPLNRMAT1NLAYERDO;
	else if (s == "dpchappplnrmatapardata") return DPCHAPPPLNRMATAPARDATA;
	else if (s == "dpchappplnrmatapardo") return DPCHAPPPLNRMATAPARDO;
	else if (s == "dpchappplnrmatdetaildata") return DPCHAPPPLNRMATDETAILDATA;
	else if (s == "dpchappplnrmatdetaildo") return DPCHAPPPLNRMATDETAILDO;
	else if (s == "dpchappplnrmatdo") return DPCHAPPPLNRMATDO;
	else if (s == "dpchappplnrmatlistdata") return DPCHAPPPLNRMATLISTDATA;
	else if (s == "dpchappplnrmatlistdo") return DPCHAPPPLNRMATLISTDO;
	else if (s == "dpchappplnrmatmod1nmaterialdata") return DPCHAPPPLNRMATMOD1NMATERIALDATA;
	else if (s == "dpchappplnrmatmod1nmaterialdo") return DPCHAPPPLNRMATMOD1NMATERIALDO;
	else if (s == "dpchappplnrmatrecdo") return DPCHAPPPLNRMATRECDO;
	else if (s == "dpchappplnrmatref1nfiledata") return DPCHAPPPLNRMATREF1NFILEDATA;
	else if (s == "dpchappplnrmatref1nfiledo") return DPCHAPPPLNRMATREF1NFILEDO;
	else if (s == "dpchappplnrnavadmindata") return DPCHAPPPLNRNAVADMINDATA;
	else if (s == "dpchappplnrnavadmindo") return DPCHAPPPLNRNAVADMINDO;
	else if (s == "dpchappplnrnavcalcdata") return DPCHAPPPLNRNAVCALCDATA;
	else if (s == "dpchappplnrnavcalcdo") return DPCHAPPPLNRNAVCALCDO;
	else if (s == "dpchappplnrnavdesigndata") return DPCHAPPPLNRNAVDESIGNDATA;
	else if (s == "dpchappplnrnavdesigndo") return DPCHAPPPLNRNAVDESIGNDO;
	else if (s == "dpchappplnrnavdo") return DPCHAPPPLNRNAVDO;
	else if (s == "dpchappplnrnavglobaldata") return DPCHAPPPLNRNAVGLOBALDATA;
	else if (s == "dpchappplnrnavglobaldo") return DPCHAPPPLNRNAVGLOBALDO;
	else if (s == "dpchappplnrnavlayoutdata") return DPCHAPPPLNRNAVLAYOUTDATA;
	else if (s == "dpchappplnrnavlayoutdo") return DPCHAPPPLNRNAVLAYOUTDO;
	else if (s == "dpchappplnrnavpredo") return DPCHAPPPLNRNAVPREDO;
	else if (s == "dpchappplnrprj1ncalcdata") return DPCHAPPPLNRPRJ1NCALCDATA;
	else if (s == "dpchappplnrprj1ncalcdo") return DPCHAPPPLNRPRJ1NCALCDO;
	else if (s == "dpchappplnrprj1ndesigndata") return DPCHAPPPLNRPRJ1NDESIGNDATA;
	else if (s == "dpchappplnrprj1ndesigndo") return DPCHAPPPLNRPRJ1NDESIGNDO;
	else if (s == "dpchappplnrprjdetaildata") return DPCHAPPPLNRPRJDETAILDATA;
	else if (s == "dpchappplnrprjdetaildo") return DPCHAPPPLNRPRJDETAILDO;
	else if (s == "dpchappplnrprjdo") return DPCHAPPPLNRPRJDO;
	else if (s == "dpchappplnrprjlistdata") return DPCHAPPPLNRPRJLISTDATA;
	else if (s == "dpchappplnrprjlistdo") return DPCHAPPPLNRPRJLISTDO;
	else if (s == "dpchappplnrprjmntapeoutdata") return DPCHAPPPLNRPRJMNTAPEOUTDATA;
	else if (s == "dpchappplnrprjmntapeoutdo") return DPCHAPPPLNRPRJMNTAPEOUTDO;
	else if (s == "dpchappplnrprjrecdo") return DPCHAPPPLNRPRJRECDO;
	else if (s == "dpchappplnrprsadetaildata") return DPCHAPPPLNRPRSADETAILDATA;
	else if (s == "dpchappplnrprsadetaildo") return DPCHAPPPLNRPRSADETAILDO;
	else if (s == "dpchappplnrprsdetaildata") return DPCHAPPPLNRPRSDETAILDATA;
	else if (s == "dpchappplnrprsdetaildo") return DPCHAPPPLNRPRSDETAILDO;
	else if (s == "dpchappplnrprsdo") return DPCHAPPPLNRPRSDO;
	else if (s == "dpchappplnrprslistdata") return DPCHAPPPLNRPRSLISTDATA;
	else if (s == "dpchappplnrprslistdo") return DPCHAPPPLNRPRSLISTDO;
	else if (s == "dpchappplnrprsrecdo") return DPCHAPPPLNRPRSRECDO;
	else if (s == "dpchappplnrresume") return DPCHAPPPLNRRESUME;
	else if (s == "dpchappplnrrtcdetaildata") return DPCHAPPPLNRRTCDETAILDATA;
	else if (s == "dpchappplnrrtcdetaildo") return DPCHAPPPLNRRTCDETAILDO;
	else if (s == "dpchappplnrrtcdo") return DPCHAPPPLNRRTCDO;
	else if (s == "dpchappplnrrtclistdata") return DPCHAPPPLNRRTCLISTDATA;
	else if (s == "dpchappplnrrtclistdo") return DPCHAPPPLNRRTCLISTDO;
	else if (s == "dpchappplnrrtcrecdo") return DPCHAPPPLNRRTCRECDO;
	else if (s == "dpchappplnrsru1nblockdata") return DPCHAPPPLNRSRU1NBLOCKDATA;
	else if (s == "dpchappplnrsru1nblockdo") return DPCHAPPPLNRSRU1NBLOCKDO;
	else if (s == "dpchappplnrsrudetaildata") return DPCHAPPPLNRSRUDETAILDATA;
	else if (s == "dpchappplnrsrudetaildo") return DPCHAPPPLNRSRUDETAILDO;
	else if (s == "dpchappplnrsrudo") return DPCHAPPPLNRSRUDO;
	else if (s == "dpchappplnrsrulistdata") return DPCHAPPPLNRSRULISTDATA;
	else if (s == "dpchappplnrsrulistdo") return DPCHAPPPLNRSRULISTDO;
	else if (s == "dpchappplnrsrumnlayerdata") return DPCHAPPPLNRSRUMNLAYERDATA;
	else if (s == "dpchappplnrsrumnlayerdo") return DPCHAPPPLNRSRUMNLAYERDO;
	else if (s == "dpchappplnrsrumnstackdata") return DPCHAPPPLNRSRUMNSTACKDATA;
	else if (s == "dpchappplnrsrumnstackdo") return DPCHAPPPLNRSRUMNSTACKDO;
	else if (s == "dpchappplnrsrurecdo") return DPCHAPPPLNRSRURECDO;
	else if (s == "dpchappplnrsrusru1nfacedata") return DPCHAPPPLNRSRUSRU1NFACEDATA;
	else if (s == "dpchappplnrsrusru1nfacedo") return DPCHAPPPLNRSRUSRU1NFACEDO;
	else if (s == "dpchappplnrstkdetaildata") return DPCHAPPPLNRSTKDETAILDATA;
	else if (s == "dpchappplnrstkdetaildo") return DPCHAPPPLNRSTKDETAILDO;
	else if (s == "dpchappplnrstkdo") return DPCHAPPPLNRSTKDO;
	else if (s == "dpchappplnrstkhk1nlayerdata") return DPCHAPPPLNRSTKHK1NLAYERDATA;
	else if (s == "dpchappplnrstkhk1nlayerdo") return DPCHAPPPLNRSTKHK1NLAYERDO;
	else if (s == "dpchappplnrstkhk1nleveldata") return DPCHAPPPLNRSTKHK1NLEVELDATA;
	else if (s == "dpchappplnrstkhk1nleveldo") return DPCHAPPPLNRSTKHK1NLEVELDO;
	else if (s == "dpchappplnrstklistdata") return DPCHAPPPLNRSTKLISTDATA;
	else if (s == "dpchappplnrstklistdo") return DPCHAPPPLNRSTKLISTDO;
	else if (s == "dpchappplnrstkmnstructuredata") return DPCHAPPPLNRSTKMNSTRUCTUREDATA;
	else if (s == "dpchappplnrstkmnstructuredo") return DPCHAPPPLNRSTKMNSTRUCTUREDO;
	else if (s == "dpchappplnrstkrecdo") return DPCHAPPPLNRSTKRECDO;
	else if (s == "dpchappplnrtpo1narraydata") return DPCHAPPPLNRTPO1NARRAYDATA;
	else if (s == "dpchappplnrtpo1narraydo") return DPCHAPPPLNRTPO1NARRAYDO;
	else if (s == "dpchappplnrtpodetaildata") return DPCHAPPPLNRTPODETAILDATA;
	else if (s == "dpchappplnrtpodetaildo") return DPCHAPPPLNRTPODETAILDO;
	else if (s == "dpchappplnrtpodo") return DPCHAPPPLNRTPODO;
	else if (s == "dpchappplnrtpohk1nreticledata") return DPCHAPPPLNRTPOHK1NRETICLEDATA;
	else if (s == "dpchappplnrtpohk1nreticledo") return DPCHAPPPLNRTPOHK1NRETICLEDO;
	else if (s == "dpchappplnrtpolistdata") return DPCHAPPPLNRTPOLISTDATA;
	else if (s == "dpchappplnrtpolistdo") return DPCHAPPPLNRTPOLISTDO;
	else if (s == "dpchappplnrtpomnprojectdata") return DPCHAPPPLNRTPOMNPROJECTDATA;
	else if (s == "dpchappplnrtpomnprojectdo") return DPCHAPPPLNRTPOMNPROJECTDO;
	else if (s == "dpchappplnrtporecdo") return DPCHAPPPLNRTPORECDO;
	else if (s == "dpchappplnrusgaaccessdata") return DPCHAPPPLNRUSGAACCESSDATA;
	else if (s == "dpchappplnrusgaaccessdo") return DPCHAPPPLNRUSGAACCESSDO;
	else if (s == "dpchappplnrusgdetaildata") return DPCHAPPPLNRUSGDETAILDATA;
	else if (s == "dpchappplnrusgdetaildo") return DPCHAPPPLNRUSGDETAILDO;
	else if (s == "dpchappplnrusgdo") return DPCHAPPPLNRUSGDO;
	else if (s == "dpchappplnrusglistdata") return DPCHAPPPLNRUSGLISTDATA;
	else if (s == "dpchappplnrusglistdo") return DPCHAPPPLNRUSGLISTDO;
	else if (s == "dpchappplnrusgmnuserdata") return DPCHAPPPLNRUSGMNUSERDATA;
	else if (s == "dpchappplnrusgmnuserdo") return DPCHAPPPLNRUSGMNUSERDO;
	else if (s == "dpchappplnrusgrecdo") return DPCHAPPPLNRUSGRECDO;
	else if (s == "dpchappplnrusr1nsessiondata") return DPCHAPPPLNRUSR1NSESSIONDATA;
	else if (s == "dpchappplnrusr1nsessiondo") return DPCHAPPPLNRUSR1NSESSIONDO;
	else if (s == "dpchappplnrusraaccessdata") return DPCHAPPPLNRUSRAACCESSDATA;
	else if (s == "dpchappplnrusraaccessdo") return DPCHAPPPLNRUSRAACCESSDO;
	else if (s == "dpchappplnrusrdetaildata") return DPCHAPPPLNRUSRDETAILDATA;
	else if (s == "dpchappplnrusrdetaildo") return DPCHAPPPLNRUSRDETAILDO;
	else if (s == "dpchappplnrusrdo") return DPCHAPPPLNRUSRDO;
	else if (s == "dpchappplnrusrlistdata") return DPCHAPPPLNRUSRLISTDATA;
	else if (s == "dpchappplnrusrlistdo") return DPCHAPPPLNRUSRLISTDO;
	else if (s == "dpchappplnrusrmnusergroupdata") return DPCHAPPPLNRUSRMNUSERGROUPDATA;
	else if (s == "dpchappplnrusrmnusergroupdo") return DPCHAPPPLNRUSRMNUSERGROUPDO;
	else if (s == "dpchappplnrusrrecdo") return DPCHAPPPLNRUSRRECDO;
	else if (s == "dpchapprootplnrlogin") return DPCHAPPROOTPLNRLOGIN;
	else if (s == "dpchengdlgplnrclcexprtxdata") return DPCHENGDLGPLNRCLCEXPRTXDATA;
	else if (s == "dpchengdlgplnrclcgenrpvdata") return DPCHENGDLGPLNRCLCGENRPVDATA;
	else if (s == "dpchengdlgplnrclcusecasedata") return DPCHENGDLGPLNRCLCUSECASEDATA;
	else if (s == "dpchengdlgplnrdsngenpltdata") return DPCHENGDLGPLNRDSNGENPLTDATA;
	else if (s == "dpchengdlgplnrfildldcpydata") return DPCHENGDLGPLNRFILDLDCPYDATA;
	else if (s == "dpchengdlgplnrnavloainidata") return DPCHENGDLGPLNRNAVLOAINIDATA;
	else if (s == "dpchengdlgplnrtpousecasedata") return DPCHENGDLGPLNRTPOUSECASEDATA;
	else if (s == "dpchengplnrack") return DPCHENGPLNRACK;
	else if (s == "dpchengplnralert") return DPCHENGPLNRALERT;
	else if (s == "dpchengplnrariamarrayenvdata") return DPCHENGPLNRARIAMARRAYENVDATA;
	else if (s == "dpchengplnraridata") return DPCHENGPLNRARIDATA;
	else if (s == "dpchengplnraridetaildata") return DPCHENGPLNRARIDETAILDATA;
	else if (s == "dpchengplnrariheadbardata") return DPCHENGPLNRARIHEADBARDATA;
	else if (s == "dpchengplnrarilistdata") return DPCHENGPLNRARILISTDATA;
	else if (s == "dpchengplnrarirecdata") return DPCHENGPLNRARIRECDATA;
	else if (s == "dpchengplnrarr1narrayitemdata") return DPCHENGPLNRARR1NARRAYITEMDATA;
	else if (s == "dpchengplnrarraenvdata") return DPCHENGPLNRARRAENVDATA;
	else if (s == "dpchengplnrarrdata") return DPCHENGPLNRARRDATA;
	else if (s == "dpchengplnrarrdetaildata") return DPCHENGPLNRARRDETAILDATA;
	else if (s == "dpchengplnrarrheadbardata") return DPCHENGPLNRARRHEADBARDATA;
	else if (s == "dpchengplnrarrhk1nreticledata") return DPCHENGPLNRARRHK1NRETICLEDATA;
	else if (s == "dpchengplnrarrkenvkeydata") return DPCHENGPLNRARRKENVKEYDATA;
	else if (s == "dpchengplnrarrlistdata") return DPCHENGPLNRARRLISTDATA;
	else if (s == "dpchengplnrarrrecdata") return DPCHENGPLNRARRRECDATA;
	else if (s == "dpchengplnrclc1nmaterialdata") return DPCHENGPLNRCLC1NMATERIALDATA;
	else if (s == "dpchengplnrclcaenvdata") return DPCHENGPLNRCLCAENVDATA;
	else if (s == "dpchengplnrclcapardata") return DPCHENGPLNRCLCAPARDATA;
	else if (s == "dpchengplnrclccal1ncalcitemdata") return DPCHENGPLNRCLCCAL1NCALCITEMDATA;
	else if (s == "dpchengplnrclcdata") return DPCHENGPLNRCLCDATA;
	else if (s == "dpchengplnrclcdetaildata") return DPCHENGPLNRCLCDETAILDATA;
	else if (s == "dpchengplnrclcheadbardata") return DPCHENGPLNRCLCHEADBARDATA;
	else if (s == "dpchengplnrclclistdata") return DPCHENGPLNRCLCLISTDATA;
	else if (s == "dpchengplnrclcmndomaindata") return DPCHENGPLNRCLCMNDOMAINDATA;
	else if (s == "dpchengplnrclcmnfiledata") return DPCHENGPLNRCLCMNFILEDATA;
	else if (s == "dpchengplnrclcpredata") return DPCHENGPLNRCLCPREDATA;
	else if (s == "dpchengplnrclcrecdata") return DPCHENGPLNRCLCRECDATA;
	else if (s == "dpchengplnrclcref1nfiledata") return DPCHENGPLNRCLCREF1NFILEDATA;
	else if (s == "dpchengplnrclcsup1ncalcdata") return DPCHENGPLNRCLCSUP1NCALCDATA;
	else if (s == "dpchengplnrclcviewdata") return DPCHENGPLNRCLCVIEWDATA;
	else if (s == "dpchengplnrcliaamcalcenvdata") return DPCHENGPLNRCLIAAMCALCENVDATA;
	else if (s == "dpchengplnrcliaamcalcpardata") return DPCHENGPLNRCLIAAMCALCPARDATA;
	else if (s == "dpchengplnrclidata") return DPCHENGPLNRCLIDATA;
	else if (s == "dpchengplnrclidetaildata") return DPCHENGPLNRCLIDETAILDATA;
	else if (s == "dpchengplnrcliheadbardata") return DPCHENGPLNRCLIHEADBARDATA;
	else if (s == "dpchengplnrclilistdata") return DPCHENGPLNRCLILISTDATA;
	else if (s == "dpchengplnrclirecdata") return DPCHENGPLNRCLIRECDATA;
	else if (s == "dpchengplnrcliref1nfiledata") return DPCHENGPLNRCLIREF1NFILEDATA;
	else if (s == "dpchengplnrconfirm") return DPCHENGPLNRCONFIRM;
	else if (s == "dpchengplnrctpaenvdata") return DPCHENGPLNRCTPAENVDATA;
	else if (s == "dpchengplnrctpapardata") return DPCHENGPLNRCTPAPARDATA;
	else if (s == "dpchengplnrctpdata") return DPCHENGPLNRCTPDATA;
	else if (s == "dpchengplnrctpdetaildata") return DPCHENGPLNRCTPDETAILDATA;
	else if (s == "dpchengplnrctpheadbardata") return DPCHENGPLNRCTPHEADBARDATA;
	else if (s == "dpchengplnrctpkcalcdomprpdata") return DPCHENGPLNRCTPKCALCDOMPRPDATA;
	else if (s == "dpchengplnrctpkcalcvardata") return DPCHENGPLNRCTPKCALCVARDATA;
	else if (s == "dpchengplnrctpkenvkeydata") return DPCHENGPLNRCTPKENVKEYDATA;
	else if (s == "dpchengplnrctpkparcatdata") return DPCHENGPLNRCTPKPARCATDATA;
	else if (s == "dpchengplnrctpkparpropdata") return DPCHENGPLNRCTPKPARPROPDATA;
	else if (s == "dpchengplnrctplistdata") return DPCHENGPLNRCTPLISTDATA;
	else if (s == "dpchengplnrctprecdata") return DPCHENGPLNRCTPRECDATA;
	else if (s == "dpchengplnrctpref1nfiledata") return DPCHENGPLNRCTPREF1NFILEDATA;
	else if (s == "dpchengplnrctpsup1ncalcdata") return DPCHENGPLNRCTPSUP1NCALCDATA;
	else if (s == "dpchengplnrctptpl1ncalcdata") return DPCHENGPLNRCTPTPL1NCALCDATA;
	else if (s == "dpchengplnrdgddata") return DPCHENGPLNRDGDDATA;
	else if (s == "dpchengplnrdgddetaildata") return DPCHENGPLNRDGDDETAILDATA;
	else if (s == "dpchengplnrdgdheadbardata") return DPCHENGPLNRDGDHEADBARDATA;
	else if (s == "dpchengplnrdgdlistdata") return DPCHENGPLNRDGDLISTDATA;
	else if (s == "dpchengplnrdgdrecdata") return DPCHENGPLNRDGDRECDATA;
	else if (s == "dpchengplnrdomdata") return DPCHENGPLNRDOMDATA;
	else if (s == "dpchengplnrdomdetaildata") return DPCHENGPLNRDOMDETAILDATA;
	else if (s == "dpchengplnrdomheadbardata") return DPCHENGPLNRDOMHEADBARDATA;
	else if (s == "dpchengplnrdomlistdata") return DPCHENGPLNRDOMLISTDATA;
	else if (s == "dpchengplnrdommncalcdata") return DPCHENGPLNRDOMMNCALCDATA;
	else if (s == "dpchengplnrdomrecdata") return DPCHENGPLNRDOMRECDATA;
	else if (s == "dpchengplnrdsn1nblockdata") return DPCHENGPLNRDSN1NBLOCKDATA;
	else if (s == "dpchengplnrdsn1nreticledata") return DPCHENGPLNRDSN1NRETICLEDATA;
	else if (s == "dpchengplnrdsndata") return DPCHENGPLNRDSNDATA;
	else if (s == "dpchengplnrdsndetaildata") return DPCHENGPLNRDSNDETAILDATA;
	else if (s == "dpchengplnrdsndrv1ndesigndata") return DPCHENGPLNRDSNDRV1NDESIGNDATA;
	else if (s == "dpchengplnrdsndsn1ndevicedata") return DPCHENGPLNRDSNDSN1NDEVICEDATA;
	else if (s == "dpchengplnrdsndsn1ndomaindata") return DPCHENGPLNRDSNDSN1NDOMAINDATA;
	else if (s == "dpchengplnrdsndsn1ndomaingddata") return DPCHENGPLNRDSNDSN1NDOMAINGDDATA;
	else if (s == "dpchengplnrdsndsn1nstackdata") return DPCHENGPLNRDSNDSN1NSTACKDATA;
	else if (s == "dpchengplnrdsnheadbardata") return DPCHENGPLNRDSNHEADBARDATA;
	else if (s == "dpchengplnrdsnhk1narcguidedata") return DPCHENGPLNRDSNHK1NARCGUIDEDATA;
	else if (s == "dpchengplnrdsnhk1nlayerdata") return DPCHENGPLNRDSNHK1NLAYERDATA;
	else if (s == "dpchengplnrdsnhk1nleveldata") return DPCHENGPLNRDSNHK1NLEVELDATA;
	else if (s == "dpchengplnrdsnhk1nlineguidedata") return DPCHENGPLNRDSNHK1NLINEGUIDEDATA;
	else if (s == "dpchengplnrdsnhk1nstructuredata") return DPCHENGPLNRDSNHK1NSTRUCTUREDATA;
	else if (s == "dpchengplnrdsnhk1nvertexdata") return DPCHENGPLNRDSNHK1NVERTEXDATA;
	else if (s == "dpchengplnrdsnlistdata") return DPCHENGPLNRDSNLISTDATA;
	else if (s == "dpchengplnrdsnmod1ndesigndata") return DPCHENGPLNRDSNMOD1NDESIGNDATA;
	else if (s == "dpchengplnrdsnpredata") return DPCHENGPLNRDSNPREDATA;
	else if (s == "dpchengplnrdsnrecdata") return DPCHENGPLNRDSNRECDATA;
	else if (s == "dpchengplnrdsnviewxydata") return DPCHENGPLNRDSNVIEWXYDATA;
	else if (s == "dpchengplnrdsnviewzdata") return DPCHENGPLNRDSNVIEWZDATA;
	else if (s == "dpchengplnrdtpapardata") return DPCHENGPLNRDTPAPARDATA;
	else if (s == "dpchengplnrdtpdata") return DPCHENGPLNRDTPDATA;
	else if (s == "dpchengplnrdtpdetaildata") return DPCHENGPLNRDTPDETAILDATA;
	else if (s == "dpchengplnrdtpheadbardata") return DPCHENGPLNRDTPHEADBARDATA;
	else if (s == "dpchengplnrdtphk1nstructuredata") return DPCHENGPLNRDTPHK1NSTRUCTUREDATA;
	else if (s == "dpchengplnrdtpkparkeydata") return DPCHENGPLNRDTPKPARKEYDATA;
	else if (s == "dpchengplnrdtplistdata") return DPCHENGPLNRDTPLISTDATA;
	else if (s == "dpchengplnrdtppredata") return DPCHENGPLNRDTPPREDATA;
	else if (s == "dpchengplnrdtprecdata") return DPCHENGPLNRDTPRECDATA;
	else if (s == "dpchengplnrdtpsup1ndevicedata") return DPCHENGPLNRDTPSUP1NDEVICEDATA;
	else if (s == "dpchengplnrdtptpl1ndevicedata") return DPCHENGPLNRDTPTPL1NDEVICEDATA;
	else if (s == "dpchengplnrdtpviewdata") return DPCHENGPLNRDTPVIEWDATA;
	else if (s == "dpchengplnrdvcapardata") return DPCHENGPLNRDVCAPARDATA;
	else if (s == "dpchengplnrdvcdata") return DPCHENGPLNRDVCDATA;
	else if (s == "dpchengplnrdvcdetaildata") return DPCHENGPLNRDVCDETAILDATA;
	else if (s == "dpchengplnrdvcheadbardata") return DPCHENGPLNRDVCHEADBARDATA;
	else if (s == "dpchengplnrdvchk1narcguidedata") return DPCHENGPLNRDVCHK1NARCGUIDEDATA;
	else if (s == "dpchengplnrdvchk1nlineguidedata") return DPCHENGPLNRDVCHK1NLINEGUIDEDATA;
	else if (s == "dpchengplnrdvchk1nstructuredata") return DPCHENGPLNRDVCHK1NSTRUCTUREDATA;
	else if (s == "dpchengplnrdvchk1nvertexdata") return DPCHENGPLNRDVCHK1NVERTEXDATA;
	else if (s == "dpchengplnrdvclistdata") return DPCHENGPLNRDVCLISTDATA;
	else if (s == "dpchengplnrdvcpredata") return DPCHENGPLNRDVCPREDATA;
	else if (s == "dpchengplnrdvcrecdata") return DPCHENGPLNRDVCRECDATA;
	else if (s == "dpchengplnrdvcsup1ndevicedata") return DPCHENGPLNRDVCSUP1NDEVICEDATA;
	else if (s == "dpchengplnrdvcviewdata") return DPCHENGPLNRDVCVIEWDATA;
	else if (s == "dpchengplnrfildata") return DPCHENGPLNRFILDATA;
	else if (s == "dpchengplnrfildetaildata") return DPCHENGPLNRFILDETAILDATA;
	else if (s == "dpchengplnrfilheadbardata") return DPCHENGPLNRFILHEADBARDATA;
	else if (s == "dpchengplnrfillistdata") return DPCHENGPLNRFILLISTDATA;
	else if (s == "dpchengplnrfilmncalcdata") return DPCHENGPLNRFILMNCALCDATA;
	else if (s == "dpchengplnrfilrecdata") return DPCHENGPLNRFILRECDATA;
	else if (s == "dpchengplnrlyr1nblockdata") return DPCHENGPLNRLYR1NBLOCKDATA;
	else if (s == "dpchengplnrlyr1nreticledata") return DPCHENGPLNRLYR1NRETICLEDATA;
	else if (s == "dpchengplnrlyrdata") return DPCHENGPLNRLYRDATA;
	else if (s == "dpchengplnrlyrdetaildata") return DPCHENGPLNRLYRDETAILDATA;
	else if (s == "dpchengplnrlyrheadbardata") return DPCHENGPLNRLYRHEADBARDATA;
	else if (s == "dpchengplnrlyrlistdata") return DPCHENGPLNRLYRLISTDATA;
	else if (s == "dpchengplnrlyrmnstructuredata") return DPCHENGPLNRLYRMNSTRUCTUREDATA;
	else if (s == "dpchengplnrlyrrecdata") return DPCHENGPLNRLYRRECDATA;
	else if (s == "dpchengplnrmat1nlayerdata") return DPCHENGPLNRMAT1NLAYERDATA;
	else if (s == "dpchengplnrmatapardata") return DPCHENGPLNRMATAPARDATA;
	else if (s == "dpchengplnrmatdata") return DPCHENGPLNRMATDATA;
	else if (s == "dpchengplnrmatdetaildata") return DPCHENGPLNRMATDETAILDATA;
	else if (s == "dpchengplnrmatheadbardata") return DPCHENGPLNRMATHEADBARDATA;
	else if (s == "dpchengplnrmatlistdata") return DPCHENGPLNRMATLISTDATA;
	else if (s == "dpchengplnrmatmod1nmaterialdata") return DPCHENGPLNRMATMOD1NMATERIALDATA;
	else if (s == "dpchengplnrmatrecdata") return DPCHENGPLNRMATRECDATA;
	else if (s == "dpchengplnrmatref1nfiledata") return DPCHENGPLNRMATREF1NFILEDATA;
	else if (s == "dpchengplnrnavadmindata") return DPCHENGPLNRNAVADMINDATA;
	else if (s == "dpchengplnrnavcalcdata") return DPCHENGPLNRNAVCALCDATA;
	else if (s == "dpchengplnrnavdata") return DPCHENGPLNRNAVDATA;
	else if (s == "dpchengplnrnavdesigndata") return DPCHENGPLNRNAVDESIGNDATA;
	else if (s == "dpchengplnrnavglobaldata") return DPCHENGPLNRNAVGLOBALDATA;
	else if (s == "dpchengplnrnavheadbardata") return DPCHENGPLNRNAVHEADBARDATA;
	else if (s == "dpchengplnrnavlayoutdata") return DPCHENGPLNRNAVLAYOUTDATA;
	else if (s == "dpchengplnrnavpredata") return DPCHENGPLNRNAVPREDATA;
	else if (s == "dpchengplnrprj1ncalcdata") return DPCHENGPLNRPRJ1NCALCDATA;
	else if (s == "dpchengplnrprj1ndesigndata") return DPCHENGPLNRPRJ1NDESIGNDATA;
	else if (s == "dpchengplnrprjdata") return DPCHENGPLNRPRJDATA;
	else if (s == "dpchengplnrprjdetaildata") return DPCHENGPLNRPRJDETAILDATA;
	else if (s == "dpchengplnrprjheadbardata") return DPCHENGPLNRPRJHEADBARDATA;
	else if (s == "dpchengplnrprjlistdata") return DPCHENGPLNRPRJLISTDATA;
	else if (s == "dpchengplnrprjmntapeoutdata") return DPCHENGPLNRPRJMNTAPEOUTDATA;
	else if (s == "dpchengplnrprjrecdata") return DPCHENGPLNRPRJRECDATA;
	else if (s == "dpchengplnrprsadetaildata") return DPCHENGPLNRPRSADETAILDATA;
	else if (s == "dpchengplnrprsdata") return DPCHENGPLNRPRSDATA;
	else if (s == "dpchengplnrprsdetaildata") return DPCHENGPLNRPRSDETAILDATA;
	else if (s == "dpchengplnrprsheadbardata") return DPCHENGPLNRPRSHEADBARDATA;
	else if (s == "dpchengplnrprslistdata") return DPCHENGPLNRPRSLISTDATA;
	else if (s == "dpchengplnrprsrecdata") return DPCHENGPLNRPRSRECDATA;
	else if (s == "dpchengplnrrtcdata") return DPCHENGPLNRRTCDATA;
	else if (s == "dpchengplnrrtcdetaildata") return DPCHENGPLNRRTCDETAILDATA;
	else if (s == "dpchengplnrrtcheadbardata") return DPCHENGPLNRRTCHEADBARDATA;
	else if (s == "dpchengplnrrtclistdata") return DPCHENGPLNRRTCLISTDATA;
	else if (s == "dpchengplnrrtcrecdata") return DPCHENGPLNRRTCRECDATA;
	else if (s == "dpchengplnrsru1nblockdata") return DPCHENGPLNRSRU1NBLOCKDATA;
	else if (s == "dpchengplnrsrudata") return DPCHENGPLNRSRUDATA;
	else if (s == "dpchengplnrsrudetaildata") return DPCHENGPLNRSRUDETAILDATA;
	else if (s == "dpchengplnrsruheadbardata") return DPCHENGPLNRSRUHEADBARDATA;
	else if (s == "dpchengplnrsrulistdata") return DPCHENGPLNRSRULISTDATA;
	else if (s == "dpchengplnrsrumnlayerdata") return DPCHENGPLNRSRUMNLAYERDATA;
	else if (s == "dpchengplnrsrumnstackdata") return DPCHENGPLNRSRUMNSTACKDATA;
	else if (s == "dpchengplnrsrurecdata") return DPCHENGPLNRSRURECDATA;
	else if (s == "dpchengplnrsrusru1nfacedata") return DPCHENGPLNRSRUSRU1NFACEDATA;
	else if (s == "dpchengplnrstkdata") return DPCHENGPLNRSTKDATA;
	else if (s == "dpchengplnrstkdetaildata") return DPCHENGPLNRSTKDETAILDATA;
	else if (s == "dpchengplnrstkheadbardata") return DPCHENGPLNRSTKHEADBARDATA;
	else if (s == "dpchengplnrstkhk1nlayerdata") return DPCHENGPLNRSTKHK1NLAYERDATA;
	else if (s == "dpchengplnrstkhk1nleveldata") return DPCHENGPLNRSTKHK1NLEVELDATA;
	else if (s == "dpchengplnrstklistdata") return DPCHENGPLNRSTKLISTDATA;
	else if (s == "dpchengplnrstkmnstructuredata") return DPCHENGPLNRSTKMNSTRUCTUREDATA;
	else if (s == "dpchengplnrstkpredata") return DPCHENGPLNRSTKPREDATA;
	else if (s == "dpchengplnrstkrecdata") return DPCHENGPLNRSTKRECDATA;
	else if (s == "dpchengplnrstkviewdata") return DPCHENGPLNRSTKVIEWDATA;
	else if (s == "dpchengplnrsuspend") return DPCHENGPLNRSUSPEND;
	else if (s == "dpchengplnrtpo1narraydata") return DPCHENGPLNRTPO1NARRAYDATA;
	else if (s == "dpchengplnrtpodata") return DPCHENGPLNRTPODATA;
	else if (s == "dpchengplnrtpodetaildata") return DPCHENGPLNRTPODETAILDATA;
	else if (s == "dpchengplnrtpofloorplandata") return DPCHENGPLNRTPOFLOORPLANDATA;
	else if (s == "dpchengplnrtpoheadbardata") return DPCHENGPLNRTPOHEADBARDATA;
	else if (s == "dpchengplnrtpohk1nreticledata") return DPCHENGPLNRTPOHK1NRETICLEDATA;
	else if (s == "dpchengplnrtpolistdata") return DPCHENGPLNRTPOLISTDATA;
	else if (s == "dpchengplnrtpomnprojectdata") return DPCHENGPLNRTPOMNPROJECTDATA;
	else if (s == "dpchengplnrtporecdata") return DPCHENGPLNRTPORECDATA;
	else if (s == "dpchengplnrusgaaccessdata") return DPCHENGPLNRUSGAACCESSDATA;
	else if (s == "dpchengplnrusgdata") return DPCHENGPLNRUSGDATA;
	else if (s == "dpchengplnrusgdetaildata") return DPCHENGPLNRUSGDETAILDATA;
	else if (s == "dpchengplnrusgheadbardata") return DPCHENGPLNRUSGHEADBARDATA;
	else if (s == "dpchengplnrusglistdata") return DPCHENGPLNRUSGLISTDATA;
	else if (s == "dpchengplnrusgmnuserdata") return DPCHENGPLNRUSGMNUSERDATA;
	else if (s == "dpchengplnrusgrecdata") return DPCHENGPLNRUSGRECDATA;
	else if (s == "dpchengplnrusr1nsessiondata") return DPCHENGPLNRUSR1NSESSIONDATA;
	else if (s == "dpchengplnrusraaccessdata") return DPCHENGPLNRUSRAACCESSDATA;
	else if (s == "dpchengplnrusrdata") return DPCHENGPLNRUSRDATA;
	else if (s == "dpchengplnrusrdetaildata") return DPCHENGPLNRUSRDETAILDATA;
	else if (s == "dpchengplnrusrheadbardata") return DPCHENGPLNRUSRHEADBARDATA;
	else if (s == "dpchengplnrusrlistdata") return DPCHENGPLNRUSRLISTDATA;
	else if (s == "dpchengplnrusrmnusergroupdata") return DPCHENGPLNRUSRMNUSERGROUPDATA;
	else if (s == "dpchengplnrusrrecdata") return DPCHENGPLNRUSRRECDATA;
	else if (s == "dpchengsessplnrdata") return DPCHENGSESSPLNRDATA;
	else if (s == "dpchinvplnr") return DPCHINVPLNR;
	else if (s == "dpchinvplnrexpcolldev") return DPCHINVPLNREXPCOLLDEV;
	else if (s == "dpchinvplnrexpcolldsn") return DPCHINVPLNREXPCOLLDSN;
	else if (s == "dpchinvplnrexpcollstk") return DPCHINVPLNREXPCOLLSTK;
	else if (s == "dpchinvplnrexpcorner") return DPCHINVPLNREXPCORNER;
	else if (s == "dpchinvplnrexpcross") return DPCHINVPLNREXPCROSS;
	else if (s == "dpchinvplnrexpdircoup") return DPCHINVPLNREXPDIRCOUP;
	else if (s == "dpchinvplnrexpdiscres") return DPCHINVPLNREXPDISCRES;
	else if (s == "dpchinvplnrexpdottext") return DPCHINVPLNREXPDOTTEXT;
	else if (s == "dpchinvplnrexpdsn") return DPCHINVPLNREXPDSN;
	else if (s == "dpchinvplnrexpgratcpl") return DPCHINVPLNREXPGRATCPL;
	else if (s == "dpchinvplnrexpgray") return DPCHINVPLNREXPGRAY;
	else if (s == "dpchinvplnrexpimage") return DPCHINVPLNREXPIMAGE;
	else if (s == "dpchinvplnrexpmarker") return DPCHINVPLNREXPMARKER;
	else if (s == "dpchinvplnrexppad") return DPCHINVPLNREXPPAD;
	else if (s == "dpchinvplnrexpphcsq") return DPCHINVPLNREXPPHCSQ;
	else if (s == "dpchinvplnrexpphcsqneg") return DPCHINVPLNREXPPHCSQNEG;
	else if (s == "dpchinvplnrexpphctrig") return DPCHINVPLNREXPPHCTRIG;
	else if (s == "dpchinvplnrexpphctrigneg") return DPCHINVPLNREXPPHCTRIGNEG;
	else if (s == "dpchinvplnrexpphotdet") return DPCHINVPLNREXPPHOTDET;
	else if (s == "dpchinvplnrexppie") return DPCHINVPLNREXPPIE;
	else if (s == "dpchinvplnrexppinout") return DPCHINVPLNREXPPINOUT;
	else if (s == "dpchinvplnrexproicadp") return DPCHINVPLNREXPROICADP;
	else if (s == "dpchinvplnrexprtresneg") return DPCHINVPLNREXPRTRESNEG;
	else if (s == "dpchinvplnrexpspring") return DPCHINVPLNREXPSPRING;
	else if (s == "dpchinvplnrexpstkpertpl") return DPCHINVPLNREXPSTKPERTPL;
	else if (s == "dpchinvplnrexpstkregfill") return DPCHINVPLNREXPSTKREGFILL;
	else if (s == "dpchinvplnrexpvanderpauw") return DPCHINVPLNREXPVANDERPAUW;
	else if (s == "dpchinvplnrexpwg") return DPCHINVPLNREXPWG;
	else if (s == "dpchinvplnrexpwgbend") return DPCHINVPLNREXPWGBEND;
	else if (s == "dpchinvplnrexpwgbendneg") return DPCHINVPLNREXPWGBENDNEG;
	else if (s == "dpchinvplnrexpwgneg") return DPCHINVPLNREXPWGNEG;
	else if (s == "dpchinvplnrexpwgsusp") return DPCHINVPLNREXPWGSUSP;
	else if (s == "dpchinvplnrexpwgtap") return DPCHINVPLNREXPWGTAP;
	else if (s == "dpchinvplnrexpwgtapneg") return DPCHINVPLNREXPWGTAPNEG;
	else if (s == "dpchinvplnrmeeptrf2d") return DPCHINVPLNRMEEPTRF2D;
	else if (s == "dpchinvplnrmeeptrf3d") return DPCHINVPLNRMEEPTRF3D;
	else if (s == "dpchinvplnrplotdat1dgnu") return DPCHINVPLNRPLOTDAT1DGNU;
	else if (s == "dpchinvplnrplotdat1dgnumult") return DPCHINVPLNRPLOTDAT1DGNUMULT;
	else if (s == "dpchinvplnrplotdevsvg") return DPCHINVPLNRPLOTDEVSVG;
	else if (s == "dpchinvplnrplotdomdat1dgnu") return DPCHINVPLNRPLOTDOMDAT1DGNU;
	else if (s == "dpchinvplnrplotdomdat2dgnu") return DPCHINVPLNRPLOTDOMDAT2DGNU;
	else if (s == "dpchinvplnrplotdomdat2dpng") return DPCHINVPLNRPLOTDOMDAT2DPNG;
	else if (s == "dpchinvplnrplotdomdat2dvid") return DPCHINVPLNRPLOTDOMDAT2DVID;
	else if (s == "dpchinvplnrplotdomzcssvg") return DPCHINVPLNRPLOTDOMZCSSVG;
	else if (s == "dpchinvplnrplotdsnxysvg") return DPCHINVPLNRPLOTDSNXYSVG;
	else if (s == "dpchinvplnrplotdsnzsvg") return DPCHINVPLNRPLOTDSNZSVG;
	else if (s == "dpchinvplnrplotstksvg") return DPCHINVPLNRPLOTSTKSVG;
	else if (s == "dpchinvplnrplottposvg") return DPCHINVPLNRPLOTTPOSVG;
	else if (s == "dpchinvplnrplottpotxt") return DPCHINVPLNRPLOTTPOTXT;
	else if (s == "dpchinvplnrrastcub") return DPCHINVPLNRRASTCUB;
	else if (s == "dpchinvplnrrastxybox") return DPCHINVPLNRRASTXYBOX;
	else if (s == "dpchinvplnrrastzline") return DPCHINVPLNRRASTZLINE;
	else if (s == "dpchinvplnrwgmodefd1d") return DPCHINVPLNRWGMODEFD1D;
	else if (s == "dpchinvplnrwgmodefd2d") return DPCHINVPLNRWGMODEFD2D;
	else if (s == "dpchinvplnrwgmodefem1d") return DPCHINVPLNRWGMODEFEM1D;
	else if (s == "dpchinvplnrwgmodefem2d") return DPCHINVPLNRWGMODEFEM2D;
	else if (s == "dpchplnrdack") return DPCHPLNRDACK;
	else if (s == "dpchplnrdquit") return DPCHPLNRDQUIT;
	else if (s == "dpchplnrdreg") return DPCHPLNRDREG;
	else if (s == "dpchplnropdreg") return DPCHPLNROPDREG;
	else if (s == "dpchplnropdunreg") return DPCHPLNROPDUNREG;
	else if (s == "dpchretplnr") return DPCHRETPLNR;
	else if (s == "dpchretplnrplotdat1dgnu") return DPCHRETPLNRPLOTDAT1DGNU;
	else if (s == "dpchretplnrplotdat1dgnumult") return DPCHRETPLNRPLOTDAT1DGNUMULT;
	else if (s == "dpchretplnrplotdevsvg") return DPCHRETPLNRPLOTDEVSVG;
	else if (s == "dpchretplnrplotdomdat1dgnu") return DPCHRETPLNRPLOTDOMDAT1DGNU;
	else if (s == "dpchretplnrplotdomdat2dgnu") return DPCHRETPLNRPLOTDOMDAT2DGNU;
	else if (s == "dpchretplnrplotdomdat2dpng") return DPCHRETPLNRPLOTDOMDAT2DPNG;
	else if (s == "dpchretplnrplotdomdat2dvid") return DPCHRETPLNRPLOTDOMDAT2DVID;
	else if (s == "dpchretplnrplotdomzcssvg") return DPCHRETPLNRPLOTDOMZCSSVG;
	else if (s == "dpchretplnrplotdsnxysvg") return DPCHRETPLNRPLOTDSNXYSVG;
	else if (s == "dpchretplnrplotdsnzsvg") return DPCHRETPLNRPLOTDSNZSVG;
	else if (s == "dpchretplnrplotstksvg") return DPCHRETPLNRPLOTSTKSVG;
	else if (s == "dpchretplnrplottposvg") return DPCHRETPLNRPLOTTPOSVG;
	else if (s == "dpchretplnrplottpotxt") return DPCHRETPLNRPLOTTPOTXT;
	else if (s == "dpchretplnrrastcub") return DPCHRETPLNRRASTCUB;
	else if (s == "dpchretplnrrastxybox") return DPCHRETPLNRRASTXYBOX;
	else if (s == "dpchretplnrrastzline") return DPCHRETPLNRRASTZLINE;
	else if (s == "dpchretplnrwgmodefd1d") return DPCHRETPLNRWGMODEFD1D;
	else if (s == "dpchretplnrwgmodefd2d") return DPCHRETPLNRWGMODEFD2D;

	return(0);
};

string VecPlnrVDpch::getSref(
			const uint ix
		) {
	if (ix == DPCHAPPDLGPLNRCLCEXPRTXDO) return("DpchAppDlgPlnrClcExprtxDo");
	else if (ix == DPCHAPPDLGPLNRCLCGENRPVDO) return("DpchAppDlgPlnrClcGenrpvDo");
	else if (ix == DPCHAPPDLGPLNRCLCUSECASEDATA) return("DpchAppDlgPlnrClcUsecaseData");
	else if (ix == DPCHAPPDLGPLNRCLCUSECASEDO) return("DpchAppDlgPlnrClcUsecaseDo");
	else if (ix == DPCHAPPDLGPLNRDSNGENPLTDO) return("DpchAppDlgPlnrDsnGenpltDo");
	else if (ix == DPCHAPPDLGPLNRFILDLDCPYDO) return("DpchAppDlgPlnrFilDldcpyDo");
	else if (ix == DPCHAPPDLGPLNRNAVLOAINIDATA) return("DpchAppDlgPlnrNavLoainiData");
	else if (ix == DPCHAPPDLGPLNRNAVLOAINIDO) return("DpchAppDlgPlnrNavLoainiDo");
	else if (ix == DPCHAPPDLGPLNRTPOUSECASEDATA) return("DpchAppDlgPlnrTpoUsecaseData");
	else if (ix == DPCHAPPDLGPLNRTPOUSECASEDO) return("DpchAppDlgPlnrTpoUsecaseDo");
	else if (ix == DPCHAPPPLNRALERT) return("DpchAppPlnrAlert");
	else if (ix == DPCHAPPPLNRARIAMARRAYENVDATA) return("DpchAppPlnrAriAMArrayEnvData");
	else if (ix == DPCHAPPPLNRARIAMARRAYENVDO) return("DpchAppPlnrAriAMArrayEnvDo");
	else if (ix == DPCHAPPPLNRARIDETAILDATA) return("DpchAppPlnrAriDetailData");
	else if (ix == DPCHAPPPLNRARIDETAILDO) return("DpchAppPlnrAriDetailDo");
	else if (ix == DPCHAPPPLNRARIDO) return("DpchAppPlnrAriDo");
	else if (ix == DPCHAPPPLNRARILISTDATA) return("DpchAppPlnrAriListData");
	else if (ix == DPCHAPPPLNRARILISTDO) return("DpchAppPlnrAriListDo");
	else if (ix == DPCHAPPPLNRARIRECDO) return("DpchAppPlnrAriRecDo");
	else if (ix == DPCHAPPPLNRARR1NARRAYITEMDATA) return("DpchAppPlnrArr1NArrayitemData");
	else if (ix == DPCHAPPPLNRARR1NARRAYITEMDO) return("DpchAppPlnrArr1NArrayitemDo");
	else if (ix == DPCHAPPPLNRARRAENVDATA) return("DpchAppPlnrArrAEnvData");
	else if (ix == DPCHAPPPLNRARRAENVDO) return("DpchAppPlnrArrAEnvDo");
	else if (ix == DPCHAPPPLNRARRDETAILDATA) return("DpchAppPlnrArrDetailData");
	else if (ix == DPCHAPPPLNRARRDETAILDO) return("DpchAppPlnrArrDetailDo");
	else if (ix == DPCHAPPPLNRARRDO) return("DpchAppPlnrArrDo");
	else if (ix == DPCHAPPPLNRARRHK1NRETICLEDATA) return("DpchAppPlnrArrHk1NReticleData");
	else if (ix == DPCHAPPPLNRARRHK1NRETICLEDO) return("DpchAppPlnrArrHk1NReticleDo");
	else if (ix == DPCHAPPPLNRARRKENVKEYDATA) return("DpchAppPlnrArrKEnvKeyData");
	else if (ix == DPCHAPPPLNRARRKENVKEYDO) return("DpchAppPlnrArrKEnvKeyDo");
	else if (ix == DPCHAPPPLNRARRLISTDATA) return("DpchAppPlnrArrListData");
	else if (ix == DPCHAPPPLNRARRLISTDO) return("DpchAppPlnrArrListDo");
	else if (ix == DPCHAPPPLNRARRRECDO) return("DpchAppPlnrArrRecDo");
	else if (ix == DPCHAPPPLNRCLC1NMATERIALDATA) return("DpchAppPlnrClc1NMaterialData");
	else if (ix == DPCHAPPPLNRCLC1NMATERIALDO) return("DpchAppPlnrClc1NMaterialDo");
	else if (ix == DPCHAPPPLNRCLCAENVDATA) return("DpchAppPlnrClcAEnvData");
	else if (ix == DPCHAPPPLNRCLCAENVDO) return("DpchAppPlnrClcAEnvDo");
	else if (ix == DPCHAPPPLNRCLCAPARDATA) return("DpchAppPlnrClcAParData");
	else if (ix == DPCHAPPPLNRCLCAPARDO) return("DpchAppPlnrClcAParDo");
	else if (ix == DPCHAPPPLNRCLCCAL1NCALCITEMDATA) return("DpchAppPlnrClcCal1NCalcitemData");
	else if (ix == DPCHAPPPLNRCLCCAL1NCALCITEMDO) return("DpchAppPlnrClcCal1NCalcitemDo");
	else if (ix == DPCHAPPPLNRCLCDETAILDATA) return("DpchAppPlnrClcDetailData");
	else if (ix == DPCHAPPPLNRCLCDETAILDO) return("DpchAppPlnrClcDetailDo");
	else if (ix == DPCHAPPPLNRCLCDO) return("DpchAppPlnrClcDo");
	else if (ix == DPCHAPPPLNRCLCLISTDATA) return("DpchAppPlnrClcListData");
	else if (ix == DPCHAPPPLNRCLCLISTDO) return("DpchAppPlnrClcListDo");
	else if (ix == DPCHAPPPLNRCLCMNDOMAINDATA) return("DpchAppPlnrClcMNDomainData");
	else if (ix == DPCHAPPPLNRCLCMNDOMAINDO) return("DpchAppPlnrClcMNDomainDo");
	else if (ix == DPCHAPPPLNRCLCMNFILEDATA) return("DpchAppPlnrClcMNFileData");
	else if (ix == DPCHAPPPLNRCLCMNFILEDO) return("DpchAppPlnrClcMNFileDo");
	else if (ix == DPCHAPPPLNRCLCRECDO) return("DpchAppPlnrClcRecDo");
	else if (ix == DPCHAPPPLNRCLCREF1NFILEDATA) return("DpchAppPlnrClcRef1NFileData");
	else if (ix == DPCHAPPPLNRCLCREF1NFILEDO) return("DpchAppPlnrClcRef1NFileDo");
	else if (ix == DPCHAPPPLNRCLCSUP1NCALCDATA) return("DpchAppPlnrClcSup1NCalcData");
	else if (ix == DPCHAPPPLNRCLCSUP1NCALCDO) return("DpchAppPlnrClcSup1NCalcDo");
	else if (ix == DPCHAPPPLNRCLIAAMCALCENVDATA) return("DpchAppPlnrCliAAMCalcEnvData");
	else if (ix == DPCHAPPPLNRCLIAAMCALCENVDO) return("DpchAppPlnrCliAAMCalcEnvDo");
	else if (ix == DPCHAPPPLNRCLIAAMCALCPARDATA) return("DpchAppPlnrCliAAMCalcParData");
	else if (ix == DPCHAPPPLNRCLIAAMCALCPARDO) return("DpchAppPlnrCliAAMCalcParDo");
	else if (ix == DPCHAPPPLNRCLIDETAILDATA) return("DpchAppPlnrCliDetailData");
	else if (ix == DPCHAPPPLNRCLIDETAILDO) return("DpchAppPlnrCliDetailDo");
	else if (ix == DPCHAPPPLNRCLIDO) return("DpchAppPlnrCliDo");
	else if (ix == DPCHAPPPLNRCLILISTDATA) return("DpchAppPlnrCliListData");
	else if (ix == DPCHAPPPLNRCLILISTDO) return("DpchAppPlnrCliListDo");
	else if (ix == DPCHAPPPLNRCLIRECDO) return("DpchAppPlnrCliRecDo");
	else if (ix == DPCHAPPPLNRCLIREF1NFILEDATA) return("DpchAppPlnrCliRef1NFileData");
	else if (ix == DPCHAPPPLNRCLIREF1NFILEDO) return("DpchAppPlnrCliRef1NFileDo");
	else if (ix == DPCHAPPPLNRCTPAENVDATA) return("DpchAppPlnrCtpAEnvData");
	else if (ix == DPCHAPPPLNRCTPAENVDO) return("DpchAppPlnrCtpAEnvDo");
	else if (ix == DPCHAPPPLNRCTPAPARDATA) return("DpchAppPlnrCtpAParData");
	else if (ix == DPCHAPPPLNRCTPAPARDO) return("DpchAppPlnrCtpAParDo");
	else if (ix == DPCHAPPPLNRCTPDETAILDATA) return("DpchAppPlnrCtpDetailData");
	else if (ix == DPCHAPPPLNRCTPDETAILDO) return("DpchAppPlnrCtpDetailDo");
	else if (ix == DPCHAPPPLNRCTPDO) return("DpchAppPlnrCtpDo");
	else if (ix == DPCHAPPPLNRCTPKCALCDOMPRPDATA) return("DpchAppPlnrCtpKCalcdomprpData");
	else if (ix == DPCHAPPPLNRCTPKCALCDOMPRPDO) return("DpchAppPlnrCtpKCalcdomprpDo");
	else if (ix == DPCHAPPPLNRCTPKCALCVARDATA) return("DpchAppPlnrCtpKCalcvarData");
	else if (ix == DPCHAPPPLNRCTPKCALCVARDO) return("DpchAppPlnrCtpKCalcvarDo");
	else if (ix == DPCHAPPPLNRCTPKENVKEYDATA) return("DpchAppPlnrCtpKEnvKeyData");
	else if (ix == DPCHAPPPLNRCTPKENVKEYDO) return("DpchAppPlnrCtpKEnvKeyDo");
	else if (ix == DPCHAPPPLNRCTPKPARCATDATA) return("DpchAppPlnrCtpKParCatData");
	else if (ix == DPCHAPPPLNRCTPKPARCATDO) return("DpchAppPlnrCtpKParCatDo");
	else if (ix == DPCHAPPPLNRCTPKPARPROPDATA) return("DpchAppPlnrCtpKParPropData");
	else if (ix == DPCHAPPPLNRCTPKPARPROPDO) return("DpchAppPlnrCtpKParPropDo");
	else if (ix == DPCHAPPPLNRCTPLISTDATA) return("DpchAppPlnrCtpListData");
	else if (ix == DPCHAPPPLNRCTPLISTDO) return("DpchAppPlnrCtpListDo");
	else if (ix == DPCHAPPPLNRCTPRECDO) return("DpchAppPlnrCtpRecDo");
	else if (ix == DPCHAPPPLNRCTPREF1NFILEDATA) return("DpchAppPlnrCtpRef1NFileData");
	else if (ix == DPCHAPPPLNRCTPREF1NFILEDO) return("DpchAppPlnrCtpRef1NFileDo");
	else if (ix == DPCHAPPPLNRCTPSUP1NCALCDATA) return("DpchAppPlnrCtpSup1NCalcData");
	else if (ix == DPCHAPPPLNRCTPSUP1NCALCDO) return("DpchAppPlnrCtpSup1NCalcDo");
	else if (ix == DPCHAPPPLNRCTPTPL1NCALCDATA) return("DpchAppPlnrCtpTpl1NCalcData");
	else if (ix == DPCHAPPPLNRCTPTPL1NCALCDO) return("DpchAppPlnrCtpTpl1NCalcDo");
	else if (ix == DPCHAPPPLNRDGDDETAILDATA) return("DpchAppPlnrDgdDetailData");
	else if (ix == DPCHAPPPLNRDGDDETAILDO) return("DpchAppPlnrDgdDetailDo");
	else if (ix == DPCHAPPPLNRDGDDO) return("DpchAppPlnrDgdDo");
	else if (ix == DPCHAPPPLNRDGDLISTDATA) return("DpchAppPlnrDgdListData");
	else if (ix == DPCHAPPPLNRDGDLISTDO) return("DpchAppPlnrDgdListDo");
	else if (ix == DPCHAPPPLNRDGDRECDO) return("DpchAppPlnrDgdRecDo");
	else if (ix == DPCHAPPPLNRDOMDETAILDATA) return("DpchAppPlnrDomDetailData");
	else if (ix == DPCHAPPPLNRDOMDETAILDO) return("DpchAppPlnrDomDetailDo");
	else if (ix == DPCHAPPPLNRDOMDO) return("DpchAppPlnrDomDo");
	else if (ix == DPCHAPPPLNRDOMLISTDATA) return("DpchAppPlnrDomListData");
	else if (ix == DPCHAPPPLNRDOMLISTDO) return("DpchAppPlnrDomListDo");
	else if (ix == DPCHAPPPLNRDOMMNCALCDATA) return("DpchAppPlnrDomMNCalcData");
	else if (ix == DPCHAPPPLNRDOMMNCALCDO) return("DpchAppPlnrDomMNCalcDo");
	else if (ix == DPCHAPPPLNRDOMRECDO) return("DpchAppPlnrDomRecDo");
	else if (ix == DPCHAPPPLNRDSN1NBLOCKDATA) return("DpchAppPlnrDsn1NBlockData");
	else if (ix == DPCHAPPPLNRDSN1NBLOCKDO) return("DpchAppPlnrDsn1NBlockDo");
	else if (ix == DPCHAPPPLNRDSN1NRETICLEDATA) return("DpchAppPlnrDsn1NReticleData");
	else if (ix == DPCHAPPPLNRDSN1NRETICLEDO) return("DpchAppPlnrDsn1NReticleDo");
	else if (ix == DPCHAPPPLNRDSNDETAILDATA) return("DpchAppPlnrDsnDetailData");
	else if (ix == DPCHAPPPLNRDSNDETAILDO) return("DpchAppPlnrDsnDetailDo");
	else if (ix == DPCHAPPPLNRDSNDO) return("DpchAppPlnrDsnDo");
	else if (ix == DPCHAPPPLNRDSNDRV1NDESIGNDATA) return("DpchAppPlnrDsnDrv1NDesignData");
	else if (ix == DPCHAPPPLNRDSNDRV1NDESIGNDO) return("DpchAppPlnrDsnDrv1NDesignDo");
	else if (ix == DPCHAPPPLNRDSNDSN1NDEVICEDATA) return("DpchAppPlnrDsnDsn1NDeviceData");
	else if (ix == DPCHAPPPLNRDSNDSN1NDEVICEDO) return("DpchAppPlnrDsnDsn1NDeviceDo");
	else if (ix == DPCHAPPPLNRDSNDSN1NDOMAINDATA) return("DpchAppPlnrDsnDsn1NDomainData");
	else if (ix == DPCHAPPPLNRDSNDSN1NDOMAINDO) return("DpchAppPlnrDsnDsn1NDomainDo");
	else if (ix == DPCHAPPPLNRDSNDSN1NDOMAINGDDATA) return("DpchAppPlnrDsnDsn1NDomaingdData");
	else if (ix == DPCHAPPPLNRDSNDSN1NDOMAINGDDO) return("DpchAppPlnrDsnDsn1NDomaingdDo");
	else if (ix == DPCHAPPPLNRDSNDSN1NSTACKDATA) return("DpchAppPlnrDsnDsn1NStackData");
	else if (ix == DPCHAPPPLNRDSNDSN1NSTACKDO) return("DpchAppPlnrDsnDsn1NStackDo");
	else if (ix == DPCHAPPPLNRDSNHK1NARCGUIDEDATA) return("DpchAppPlnrDsnHk1NArcguideData");
	else if (ix == DPCHAPPPLNRDSNHK1NARCGUIDEDO) return("DpchAppPlnrDsnHk1NArcguideDo");
	else if (ix == DPCHAPPPLNRDSNHK1NLAYERDATA) return("DpchAppPlnrDsnHk1NLayerData");
	else if (ix == DPCHAPPPLNRDSNHK1NLAYERDO) return("DpchAppPlnrDsnHk1NLayerDo");
	else if (ix == DPCHAPPPLNRDSNHK1NLEVELDATA) return("DpchAppPlnrDsnHk1NLevelData");
	else if (ix == DPCHAPPPLNRDSNHK1NLEVELDO) return("DpchAppPlnrDsnHk1NLevelDo");
	else if (ix == DPCHAPPPLNRDSNHK1NLINEGUIDEDATA) return("DpchAppPlnrDsnHk1NLineguideData");
	else if (ix == DPCHAPPPLNRDSNHK1NLINEGUIDEDO) return("DpchAppPlnrDsnHk1NLineguideDo");
	else if (ix == DPCHAPPPLNRDSNHK1NSTRUCTUREDATA) return("DpchAppPlnrDsnHk1NStructureData");
	else if (ix == DPCHAPPPLNRDSNHK1NSTRUCTUREDO) return("DpchAppPlnrDsnHk1NStructureDo");
	else if (ix == DPCHAPPPLNRDSNHK1NVERTEXDATA) return("DpchAppPlnrDsnHk1NVertexData");
	else if (ix == DPCHAPPPLNRDSNHK1NVERTEXDO) return("DpchAppPlnrDsnHk1NVertexDo");
	else if (ix == DPCHAPPPLNRDSNLISTDATA) return("DpchAppPlnrDsnListData");
	else if (ix == DPCHAPPPLNRDSNLISTDO) return("DpchAppPlnrDsnListDo");
	else if (ix == DPCHAPPPLNRDSNMOD1NDESIGNDATA) return("DpchAppPlnrDsnMod1NDesignData");
	else if (ix == DPCHAPPPLNRDSNMOD1NDESIGNDO) return("DpchAppPlnrDsnMod1NDesignDo");
	else if (ix == DPCHAPPPLNRDSNRECDO) return("DpchAppPlnrDsnRecDo");
	else if (ix == DPCHAPPPLNRDTPAPARDATA) return("DpchAppPlnrDtpAParData");
	else if (ix == DPCHAPPPLNRDTPAPARDO) return("DpchAppPlnrDtpAParDo");
	else if (ix == DPCHAPPPLNRDTPDETAILDATA) return("DpchAppPlnrDtpDetailData");
	else if (ix == DPCHAPPPLNRDTPDETAILDO) return("DpchAppPlnrDtpDetailDo");
	else if (ix == DPCHAPPPLNRDTPDO) return("DpchAppPlnrDtpDo");
	else if (ix == DPCHAPPPLNRDTPHK1NSTRUCTUREDATA) return("DpchAppPlnrDtpHk1NStructureData");
	else if (ix == DPCHAPPPLNRDTPHK1NSTRUCTUREDO) return("DpchAppPlnrDtpHk1NStructureDo");
	else if (ix == DPCHAPPPLNRDTPKPARKEYDATA) return("DpchAppPlnrDtpKParKeyData");
	else if (ix == DPCHAPPPLNRDTPKPARKEYDO) return("DpchAppPlnrDtpKParKeyDo");
	else if (ix == DPCHAPPPLNRDTPLISTDATA) return("DpchAppPlnrDtpListData");
	else if (ix == DPCHAPPPLNRDTPLISTDO) return("DpchAppPlnrDtpListDo");
	else if (ix == DPCHAPPPLNRDTPRECDO) return("DpchAppPlnrDtpRecDo");
	else if (ix == DPCHAPPPLNRDTPSUP1NDEVICEDATA) return("DpchAppPlnrDtpSup1NDeviceData");
	else if (ix == DPCHAPPPLNRDTPSUP1NDEVICEDO) return("DpchAppPlnrDtpSup1NDeviceDo");
	else if (ix == DPCHAPPPLNRDTPTPL1NDEVICEDATA) return("DpchAppPlnrDtpTpl1NDeviceData");
	else if (ix == DPCHAPPPLNRDTPTPL1NDEVICEDO) return("DpchAppPlnrDtpTpl1NDeviceDo");
	else if (ix == DPCHAPPPLNRDVCAPARDATA) return("DpchAppPlnrDvcAParData");
	else if (ix == DPCHAPPPLNRDVCAPARDO) return("DpchAppPlnrDvcAParDo");
	else if (ix == DPCHAPPPLNRDVCDETAILDATA) return("DpchAppPlnrDvcDetailData");
	else if (ix == DPCHAPPPLNRDVCDETAILDO) return("DpchAppPlnrDvcDetailDo");
	else if (ix == DPCHAPPPLNRDVCDO) return("DpchAppPlnrDvcDo");
	else if (ix == DPCHAPPPLNRDVCHK1NARCGUIDEDATA) return("DpchAppPlnrDvcHk1NArcguideData");
	else if (ix == DPCHAPPPLNRDVCHK1NARCGUIDEDO) return("DpchAppPlnrDvcHk1NArcguideDo");
	else if (ix == DPCHAPPPLNRDVCHK1NLINEGUIDEDATA) return("DpchAppPlnrDvcHk1NLineguideData");
	else if (ix == DPCHAPPPLNRDVCHK1NLINEGUIDEDO) return("DpchAppPlnrDvcHk1NLineguideDo");
	else if (ix == DPCHAPPPLNRDVCHK1NSTRUCTUREDATA) return("DpchAppPlnrDvcHk1NStructureData");
	else if (ix == DPCHAPPPLNRDVCHK1NSTRUCTUREDO) return("DpchAppPlnrDvcHk1NStructureDo");
	else if (ix == DPCHAPPPLNRDVCHK1NVERTEXDATA) return("DpchAppPlnrDvcHk1NVertexData");
	else if (ix == DPCHAPPPLNRDVCHK1NVERTEXDO) return("DpchAppPlnrDvcHk1NVertexDo");
	else if (ix == DPCHAPPPLNRDVCLISTDATA) return("DpchAppPlnrDvcListData");
	else if (ix == DPCHAPPPLNRDVCLISTDO) return("DpchAppPlnrDvcListDo");
	else if (ix == DPCHAPPPLNRDVCRECDO) return("DpchAppPlnrDvcRecDo");
	else if (ix == DPCHAPPPLNRDVCSUP1NDEVICEDATA) return("DpchAppPlnrDvcSup1NDeviceData");
	else if (ix == DPCHAPPPLNRDVCSUP1NDEVICEDO) return("DpchAppPlnrDvcSup1NDeviceDo");
	else if (ix == DPCHAPPPLNRFILDETAILDATA) return("DpchAppPlnrFilDetailData");
	else if (ix == DPCHAPPPLNRFILDETAILDO) return("DpchAppPlnrFilDetailDo");
	else if (ix == DPCHAPPPLNRFILDO) return("DpchAppPlnrFilDo");
	else if (ix == DPCHAPPPLNRFILLISTDATA) return("DpchAppPlnrFilListData");
	else if (ix == DPCHAPPPLNRFILLISTDO) return("DpchAppPlnrFilListDo");
	else if (ix == DPCHAPPPLNRFILMNCALCDATA) return("DpchAppPlnrFilMNCalcData");
	else if (ix == DPCHAPPPLNRFILMNCALCDO) return("DpchAppPlnrFilMNCalcDo");
	else if (ix == DPCHAPPPLNRFILRECDO) return("DpchAppPlnrFilRecDo");
	else if (ix == DPCHAPPPLNRINIT) return("DpchAppPlnrInit");
	else if (ix == DPCHAPPPLNRLYR1NBLOCKDATA) return("DpchAppPlnrLyr1NBlockData");
	else if (ix == DPCHAPPPLNRLYR1NBLOCKDO) return("DpchAppPlnrLyr1NBlockDo");
	else if (ix == DPCHAPPPLNRLYR1NRETICLEDATA) return("DpchAppPlnrLyr1NReticleData");
	else if (ix == DPCHAPPPLNRLYR1NRETICLEDO) return("DpchAppPlnrLyr1NReticleDo");
	else if (ix == DPCHAPPPLNRLYRDETAILDATA) return("DpchAppPlnrLyrDetailData");
	else if (ix == DPCHAPPPLNRLYRDETAILDO) return("DpchAppPlnrLyrDetailDo");
	else if (ix == DPCHAPPPLNRLYRDO) return("DpchAppPlnrLyrDo");
	else if (ix == DPCHAPPPLNRLYRLISTDATA) return("DpchAppPlnrLyrListData");
	else if (ix == DPCHAPPPLNRLYRLISTDO) return("DpchAppPlnrLyrListDo");
	else if (ix == DPCHAPPPLNRLYRMNSTRUCTUREDATA) return("DpchAppPlnrLyrMNStructureData");
	else if (ix == DPCHAPPPLNRLYRMNSTRUCTUREDO) return("DpchAppPlnrLyrMNStructureDo");
	else if (ix == DPCHAPPPLNRLYRRECDO) return("DpchAppPlnrLyrRecDo");
	else if (ix == DPCHAPPPLNRMAT1NLAYERDATA) return("DpchAppPlnrMat1NLayerData");
	else if (ix == DPCHAPPPLNRMAT1NLAYERDO) return("DpchAppPlnrMat1NLayerDo");
	else if (ix == DPCHAPPPLNRMATAPARDATA) return("DpchAppPlnrMatAParData");
	else if (ix == DPCHAPPPLNRMATAPARDO) return("DpchAppPlnrMatAParDo");
	else if (ix == DPCHAPPPLNRMATDETAILDATA) return("DpchAppPlnrMatDetailData");
	else if (ix == DPCHAPPPLNRMATDETAILDO) return("DpchAppPlnrMatDetailDo");
	else if (ix == DPCHAPPPLNRMATDO) return("DpchAppPlnrMatDo");
	else if (ix == DPCHAPPPLNRMATLISTDATA) return("DpchAppPlnrMatListData");
	else if (ix == DPCHAPPPLNRMATLISTDO) return("DpchAppPlnrMatListDo");
	else if (ix == DPCHAPPPLNRMATMOD1NMATERIALDATA) return("DpchAppPlnrMatMod1NMaterialData");
	else if (ix == DPCHAPPPLNRMATMOD1NMATERIALDO) return("DpchAppPlnrMatMod1NMaterialDo");
	else if (ix == DPCHAPPPLNRMATRECDO) return("DpchAppPlnrMatRecDo");
	else if (ix == DPCHAPPPLNRMATREF1NFILEDATA) return("DpchAppPlnrMatRef1NFileData");
	else if (ix == DPCHAPPPLNRMATREF1NFILEDO) return("DpchAppPlnrMatRef1NFileDo");
	else if (ix == DPCHAPPPLNRNAVADMINDATA) return("DpchAppPlnrNavAdminData");
	else if (ix == DPCHAPPPLNRNAVADMINDO) return("DpchAppPlnrNavAdminDo");
	else if (ix == DPCHAPPPLNRNAVCALCDATA) return("DpchAppPlnrNavCalcData");
	else if (ix == DPCHAPPPLNRNAVCALCDO) return("DpchAppPlnrNavCalcDo");
	else if (ix == DPCHAPPPLNRNAVDESIGNDATA) return("DpchAppPlnrNavDesignData");
	else if (ix == DPCHAPPPLNRNAVDESIGNDO) return("DpchAppPlnrNavDesignDo");
	else if (ix == DPCHAPPPLNRNAVDO) return("DpchAppPlnrNavDo");
	else if (ix == DPCHAPPPLNRNAVGLOBALDATA) return("DpchAppPlnrNavGlobalData");
	else if (ix == DPCHAPPPLNRNAVGLOBALDO) return("DpchAppPlnrNavGlobalDo");
	else if (ix == DPCHAPPPLNRNAVLAYOUTDATA) return("DpchAppPlnrNavLayoutData");
	else if (ix == DPCHAPPPLNRNAVLAYOUTDO) return("DpchAppPlnrNavLayoutDo");
	else if (ix == DPCHAPPPLNRNAVPREDO) return("DpchAppPlnrNavPreDo");
	else if (ix == DPCHAPPPLNRPRJ1NCALCDATA) return("DpchAppPlnrPrj1NCalcData");
	else if (ix == DPCHAPPPLNRPRJ1NCALCDO) return("DpchAppPlnrPrj1NCalcDo");
	else if (ix == DPCHAPPPLNRPRJ1NDESIGNDATA) return("DpchAppPlnrPrj1NDesignData");
	else if (ix == DPCHAPPPLNRPRJ1NDESIGNDO) return("DpchAppPlnrPrj1NDesignDo");
	else if (ix == DPCHAPPPLNRPRJDETAILDATA) return("DpchAppPlnrPrjDetailData");
	else if (ix == DPCHAPPPLNRPRJDETAILDO) return("DpchAppPlnrPrjDetailDo");
	else if (ix == DPCHAPPPLNRPRJDO) return("DpchAppPlnrPrjDo");
	else if (ix == DPCHAPPPLNRPRJLISTDATA) return("DpchAppPlnrPrjListData");
	else if (ix == DPCHAPPPLNRPRJLISTDO) return("DpchAppPlnrPrjListDo");
	else if (ix == DPCHAPPPLNRPRJMNTAPEOUTDATA) return("DpchAppPlnrPrjMNTapeoutData");
	else if (ix == DPCHAPPPLNRPRJMNTAPEOUTDO) return("DpchAppPlnrPrjMNTapeoutDo");
	else if (ix == DPCHAPPPLNRPRJRECDO) return("DpchAppPlnrPrjRecDo");
	else if (ix == DPCHAPPPLNRPRSADETAILDATA) return("DpchAppPlnrPrsADetailData");
	else if (ix == DPCHAPPPLNRPRSADETAILDO) return("DpchAppPlnrPrsADetailDo");
	else if (ix == DPCHAPPPLNRPRSDETAILDATA) return("DpchAppPlnrPrsDetailData");
	else if (ix == DPCHAPPPLNRPRSDETAILDO) return("DpchAppPlnrPrsDetailDo");
	else if (ix == DPCHAPPPLNRPRSDO) return("DpchAppPlnrPrsDo");
	else if (ix == DPCHAPPPLNRPRSLISTDATA) return("DpchAppPlnrPrsListData");
	else if (ix == DPCHAPPPLNRPRSLISTDO) return("DpchAppPlnrPrsListDo");
	else if (ix == DPCHAPPPLNRPRSRECDO) return("DpchAppPlnrPrsRecDo");
	else if (ix == DPCHAPPPLNRRESUME) return("DpchAppPlnrResume");
	else if (ix == DPCHAPPPLNRRTCDETAILDATA) return("DpchAppPlnrRtcDetailData");
	else if (ix == DPCHAPPPLNRRTCDETAILDO) return("DpchAppPlnrRtcDetailDo");
	else if (ix == DPCHAPPPLNRRTCDO) return("DpchAppPlnrRtcDo");
	else if (ix == DPCHAPPPLNRRTCLISTDATA) return("DpchAppPlnrRtcListData");
	else if (ix == DPCHAPPPLNRRTCLISTDO) return("DpchAppPlnrRtcListDo");
	else if (ix == DPCHAPPPLNRRTCRECDO) return("DpchAppPlnrRtcRecDo");
	else if (ix == DPCHAPPPLNRSRU1NBLOCKDATA) return("DpchAppPlnrSru1NBlockData");
	else if (ix == DPCHAPPPLNRSRU1NBLOCKDO) return("DpchAppPlnrSru1NBlockDo");
	else if (ix == DPCHAPPPLNRSRUDETAILDATA) return("DpchAppPlnrSruDetailData");
	else if (ix == DPCHAPPPLNRSRUDETAILDO) return("DpchAppPlnrSruDetailDo");
	else if (ix == DPCHAPPPLNRSRUDO) return("DpchAppPlnrSruDo");
	else if (ix == DPCHAPPPLNRSRULISTDATA) return("DpchAppPlnrSruListData");
	else if (ix == DPCHAPPPLNRSRULISTDO) return("DpchAppPlnrSruListDo");
	else if (ix == DPCHAPPPLNRSRUMNLAYERDATA) return("DpchAppPlnrSruMNLayerData");
	else if (ix == DPCHAPPPLNRSRUMNLAYERDO) return("DpchAppPlnrSruMNLayerDo");
	else if (ix == DPCHAPPPLNRSRUMNSTACKDATA) return("DpchAppPlnrSruMNStackData");
	else if (ix == DPCHAPPPLNRSRUMNSTACKDO) return("DpchAppPlnrSruMNStackDo");
	else if (ix == DPCHAPPPLNRSRURECDO) return("DpchAppPlnrSruRecDo");
	else if (ix == DPCHAPPPLNRSRUSRU1NFACEDATA) return("DpchAppPlnrSruSru1NFaceData");
	else if (ix == DPCHAPPPLNRSRUSRU1NFACEDO) return("DpchAppPlnrSruSru1NFaceDo");
	else if (ix == DPCHAPPPLNRSTKDETAILDATA) return("DpchAppPlnrStkDetailData");
	else if (ix == DPCHAPPPLNRSTKDETAILDO) return("DpchAppPlnrStkDetailDo");
	else if (ix == DPCHAPPPLNRSTKDO) return("DpchAppPlnrStkDo");
	else if (ix == DPCHAPPPLNRSTKHK1NLAYERDATA) return("DpchAppPlnrStkHk1NLayerData");
	else if (ix == DPCHAPPPLNRSTKHK1NLAYERDO) return("DpchAppPlnrStkHk1NLayerDo");
	else if (ix == DPCHAPPPLNRSTKHK1NLEVELDATA) return("DpchAppPlnrStkHk1NLevelData");
	else if (ix == DPCHAPPPLNRSTKHK1NLEVELDO) return("DpchAppPlnrStkHk1NLevelDo");
	else if (ix == DPCHAPPPLNRSTKLISTDATA) return("DpchAppPlnrStkListData");
	else if (ix == DPCHAPPPLNRSTKLISTDO) return("DpchAppPlnrStkListDo");
	else if (ix == DPCHAPPPLNRSTKMNSTRUCTUREDATA) return("DpchAppPlnrStkMNStructureData");
	else if (ix == DPCHAPPPLNRSTKMNSTRUCTUREDO) return("DpchAppPlnrStkMNStructureDo");
	else if (ix == DPCHAPPPLNRSTKRECDO) return("DpchAppPlnrStkRecDo");
	else if (ix == DPCHAPPPLNRTPO1NARRAYDATA) return("DpchAppPlnrTpo1NArrayData");
	else if (ix == DPCHAPPPLNRTPO1NARRAYDO) return("DpchAppPlnrTpo1NArrayDo");
	else if (ix == DPCHAPPPLNRTPODETAILDATA) return("DpchAppPlnrTpoDetailData");
	else if (ix == DPCHAPPPLNRTPODETAILDO) return("DpchAppPlnrTpoDetailDo");
	else if (ix == DPCHAPPPLNRTPODO) return("DpchAppPlnrTpoDo");
	else if (ix == DPCHAPPPLNRTPOHK1NRETICLEDATA) return("DpchAppPlnrTpoHk1NReticleData");
	else if (ix == DPCHAPPPLNRTPOHK1NRETICLEDO) return("DpchAppPlnrTpoHk1NReticleDo");
	else if (ix == DPCHAPPPLNRTPOLISTDATA) return("DpchAppPlnrTpoListData");
	else if (ix == DPCHAPPPLNRTPOLISTDO) return("DpchAppPlnrTpoListDo");
	else if (ix == DPCHAPPPLNRTPOMNPROJECTDATA) return("DpchAppPlnrTpoMNProjectData");
	else if (ix == DPCHAPPPLNRTPOMNPROJECTDO) return("DpchAppPlnrTpoMNProjectDo");
	else if (ix == DPCHAPPPLNRTPORECDO) return("DpchAppPlnrTpoRecDo");
	else if (ix == DPCHAPPPLNRUSGAACCESSDATA) return("DpchAppPlnrUsgAAccessData");
	else if (ix == DPCHAPPPLNRUSGAACCESSDO) return("DpchAppPlnrUsgAAccessDo");
	else if (ix == DPCHAPPPLNRUSGDETAILDATA) return("DpchAppPlnrUsgDetailData");
	else if (ix == DPCHAPPPLNRUSGDETAILDO) return("DpchAppPlnrUsgDetailDo");
	else if (ix == DPCHAPPPLNRUSGDO) return("DpchAppPlnrUsgDo");
	else if (ix == DPCHAPPPLNRUSGLISTDATA) return("DpchAppPlnrUsgListData");
	else if (ix == DPCHAPPPLNRUSGLISTDO) return("DpchAppPlnrUsgListDo");
	else if (ix == DPCHAPPPLNRUSGMNUSERDATA) return("DpchAppPlnrUsgMNUserData");
	else if (ix == DPCHAPPPLNRUSGMNUSERDO) return("DpchAppPlnrUsgMNUserDo");
	else if (ix == DPCHAPPPLNRUSGRECDO) return("DpchAppPlnrUsgRecDo");
	else if (ix == DPCHAPPPLNRUSR1NSESSIONDATA) return("DpchAppPlnrUsr1NSessionData");
	else if (ix == DPCHAPPPLNRUSR1NSESSIONDO) return("DpchAppPlnrUsr1NSessionDo");
	else if (ix == DPCHAPPPLNRUSRAACCESSDATA) return("DpchAppPlnrUsrAAccessData");
	else if (ix == DPCHAPPPLNRUSRAACCESSDO) return("DpchAppPlnrUsrAAccessDo");
	else if (ix == DPCHAPPPLNRUSRDETAILDATA) return("DpchAppPlnrUsrDetailData");
	else if (ix == DPCHAPPPLNRUSRDETAILDO) return("DpchAppPlnrUsrDetailDo");
	else if (ix == DPCHAPPPLNRUSRDO) return("DpchAppPlnrUsrDo");
	else if (ix == DPCHAPPPLNRUSRLISTDATA) return("DpchAppPlnrUsrListData");
	else if (ix == DPCHAPPPLNRUSRLISTDO) return("DpchAppPlnrUsrListDo");
	else if (ix == DPCHAPPPLNRUSRMNUSERGROUPDATA) return("DpchAppPlnrUsrMNUsergroupData");
	else if (ix == DPCHAPPPLNRUSRMNUSERGROUPDO) return("DpchAppPlnrUsrMNUsergroupDo");
	else if (ix == DPCHAPPPLNRUSRRECDO) return("DpchAppPlnrUsrRecDo");
	else if (ix == DPCHAPPROOTPLNRLOGIN) return("DpchAppRootPlnrLogin");
	else if (ix == DPCHENGDLGPLNRCLCEXPRTXDATA) return("DpchEngDlgPlnrClcExprtxData");
	else if (ix == DPCHENGDLGPLNRCLCGENRPVDATA) return("DpchEngDlgPlnrClcGenrpvData");
	else if (ix == DPCHENGDLGPLNRCLCUSECASEDATA) return("DpchEngDlgPlnrClcUsecaseData");
	else if (ix == DPCHENGDLGPLNRDSNGENPLTDATA) return("DpchEngDlgPlnrDsnGenpltData");
	else if (ix == DPCHENGDLGPLNRFILDLDCPYDATA) return("DpchEngDlgPlnrFilDldcpyData");
	else if (ix == DPCHENGDLGPLNRNAVLOAINIDATA) return("DpchEngDlgPlnrNavLoainiData");
	else if (ix == DPCHENGDLGPLNRTPOUSECASEDATA) return("DpchEngDlgPlnrTpoUsecaseData");
	else if (ix == DPCHENGPLNRACK) return("DpchEngPlnrAck");
	else if (ix == DPCHENGPLNRALERT) return("DpchEngPlnrAlert");
	else if (ix == DPCHENGPLNRARIAMARRAYENVDATA) return("DpchEngPlnrAriAMArrayEnvData");
	else if (ix == DPCHENGPLNRARIDATA) return("DpchEngPlnrAriData");
	else if (ix == DPCHENGPLNRARIDETAILDATA) return("DpchEngPlnrAriDetailData");
	else if (ix == DPCHENGPLNRARIHEADBARDATA) return("DpchEngPlnrAriHeadbarData");
	else if (ix == DPCHENGPLNRARILISTDATA) return("DpchEngPlnrAriListData");
	else if (ix == DPCHENGPLNRARIRECDATA) return("DpchEngPlnrAriRecData");
	else if (ix == DPCHENGPLNRARR1NARRAYITEMDATA) return("DpchEngPlnrArr1NArrayitemData");
	else if (ix == DPCHENGPLNRARRAENVDATA) return("DpchEngPlnrArrAEnvData");
	else if (ix == DPCHENGPLNRARRDATA) return("DpchEngPlnrArrData");
	else if (ix == DPCHENGPLNRARRDETAILDATA) return("DpchEngPlnrArrDetailData");
	else if (ix == DPCHENGPLNRARRHEADBARDATA) return("DpchEngPlnrArrHeadbarData");
	else if (ix == DPCHENGPLNRARRHK1NRETICLEDATA) return("DpchEngPlnrArrHk1NReticleData");
	else if (ix == DPCHENGPLNRARRKENVKEYDATA) return("DpchEngPlnrArrKEnvKeyData");
	else if (ix == DPCHENGPLNRARRLISTDATA) return("DpchEngPlnrArrListData");
	else if (ix == DPCHENGPLNRARRRECDATA) return("DpchEngPlnrArrRecData");
	else if (ix == DPCHENGPLNRCLC1NMATERIALDATA) return("DpchEngPlnrClc1NMaterialData");
	else if (ix == DPCHENGPLNRCLCAENVDATA) return("DpchEngPlnrClcAEnvData");
	else if (ix == DPCHENGPLNRCLCAPARDATA) return("DpchEngPlnrClcAParData");
	else if (ix == DPCHENGPLNRCLCCAL1NCALCITEMDATA) return("DpchEngPlnrClcCal1NCalcitemData");
	else if (ix == DPCHENGPLNRCLCDATA) return("DpchEngPlnrClcData");
	else if (ix == DPCHENGPLNRCLCDETAILDATA) return("DpchEngPlnrClcDetailData");
	else if (ix == DPCHENGPLNRCLCHEADBARDATA) return("DpchEngPlnrClcHeadbarData");
	else if (ix == DPCHENGPLNRCLCLISTDATA) return("DpchEngPlnrClcListData");
	else if (ix == DPCHENGPLNRCLCMNDOMAINDATA) return("DpchEngPlnrClcMNDomainData");
	else if (ix == DPCHENGPLNRCLCMNFILEDATA) return("DpchEngPlnrClcMNFileData");
	else if (ix == DPCHENGPLNRCLCPREDATA) return("DpchEngPlnrClcPreData");
	else if (ix == DPCHENGPLNRCLCRECDATA) return("DpchEngPlnrClcRecData");
	else if (ix == DPCHENGPLNRCLCREF1NFILEDATA) return("DpchEngPlnrClcRef1NFileData");
	else if (ix == DPCHENGPLNRCLCSUP1NCALCDATA) return("DpchEngPlnrClcSup1NCalcData");
	else if (ix == DPCHENGPLNRCLCVIEWDATA) return("DpchEngPlnrClcViewData");
	else if (ix == DPCHENGPLNRCLIAAMCALCENVDATA) return("DpchEngPlnrCliAAMCalcEnvData");
	else if (ix == DPCHENGPLNRCLIAAMCALCPARDATA) return("DpchEngPlnrCliAAMCalcParData");
	else if (ix == DPCHENGPLNRCLIDATA) return("DpchEngPlnrCliData");
	else if (ix == DPCHENGPLNRCLIDETAILDATA) return("DpchEngPlnrCliDetailData");
	else if (ix == DPCHENGPLNRCLIHEADBARDATA) return("DpchEngPlnrCliHeadbarData");
	else if (ix == DPCHENGPLNRCLILISTDATA) return("DpchEngPlnrCliListData");
	else if (ix == DPCHENGPLNRCLIRECDATA) return("DpchEngPlnrCliRecData");
	else if (ix == DPCHENGPLNRCLIREF1NFILEDATA) return("DpchEngPlnrCliRef1NFileData");
	else if (ix == DPCHENGPLNRCONFIRM) return("DpchEngPlnrConfirm");
	else if (ix == DPCHENGPLNRCTPAENVDATA) return("DpchEngPlnrCtpAEnvData");
	else if (ix == DPCHENGPLNRCTPAPARDATA) return("DpchEngPlnrCtpAParData");
	else if (ix == DPCHENGPLNRCTPDATA) return("DpchEngPlnrCtpData");
	else if (ix == DPCHENGPLNRCTPDETAILDATA) return("DpchEngPlnrCtpDetailData");
	else if (ix == DPCHENGPLNRCTPHEADBARDATA) return("DpchEngPlnrCtpHeadbarData");
	else if (ix == DPCHENGPLNRCTPKCALCDOMPRPDATA) return("DpchEngPlnrCtpKCalcdomprpData");
	else if (ix == DPCHENGPLNRCTPKCALCVARDATA) return("DpchEngPlnrCtpKCalcvarData");
	else if (ix == DPCHENGPLNRCTPKENVKEYDATA) return("DpchEngPlnrCtpKEnvKeyData");
	else if (ix == DPCHENGPLNRCTPKPARCATDATA) return("DpchEngPlnrCtpKParCatData");
	else if (ix == DPCHENGPLNRCTPKPARPROPDATA) return("DpchEngPlnrCtpKParPropData");
	else if (ix == DPCHENGPLNRCTPLISTDATA) return("DpchEngPlnrCtpListData");
	else if (ix == DPCHENGPLNRCTPRECDATA) return("DpchEngPlnrCtpRecData");
	else if (ix == DPCHENGPLNRCTPREF1NFILEDATA) return("DpchEngPlnrCtpRef1NFileData");
	else if (ix == DPCHENGPLNRCTPSUP1NCALCDATA) return("DpchEngPlnrCtpSup1NCalcData");
	else if (ix == DPCHENGPLNRCTPTPL1NCALCDATA) return("DpchEngPlnrCtpTpl1NCalcData");
	else if (ix == DPCHENGPLNRDGDDATA) return("DpchEngPlnrDgdData");
	else if (ix == DPCHENGPLNRDGDDETAILDATA) return("DpchEngPlnrDgdDetailData");
	else if (ix == DPCHENGPLNRDGDHEADBARDATA) return("DpchEngPlnrDgdHeadbarData");
	else if (ix == DPCHENGPLNRDGDLISTDATA) return("DpchEngPlnrDgdListData");
	else if (ix == DPCHENGPLNRDGDRECDATA) return("DpchEngPlnrDgdRecData");
	else if (ix == DPCHENGPLNRDOMDATA) return("DpchEngPlnrDomData");
	else if (ix == DPCHENGPLNRDOMDETAILDATA) return("DpchEngPlnrDomDetailData");
	else if (ix == DPCHENGPLNRDOMHEADBARDATA) return("DpchEngPlnrDomHeadbarData");
	else if (ix == DPCHENGPLNRDOMLISTDATA) return("DpchEngPlnrDomListData");
	else if (ix == DPCHENGPLNRDOMMNCALCDATA) return("DpchEngPlnrDomMNCalcData");
	else if (ix == DPCHENGPLNRDOMRECDATA) return("DpchEngPlnrDomRecData");
	else if (ix == DPCHENGPLNRDSN1NBLOCKDATA) return("DpchEngPlnrDsn1NBlockData");
	else if (ix == DPCHENGPLNRDSN1NRETICLEDATA) return("DpchEngPlnrDsn1NReticleData");
	else if (ix == DPCHENGPLNRDSNDATA) return("DpchEngPlnrDsnData");
	else if (ix == DPCHENGPLNRDSNDETAILDATA) return("DpchEngPlnrDsnDetailData");
	else if (ix == DPCHENGPLNRDSNDRV1NDESIGNDATA) return("DpchEngPlnrDsnDrv1NDesignData");
	else if (ix == DPCHENGPLNRDSNDSN1NDEVICEDATA) return("DpchEngPlnrDsnDsn1NDeviceData");
	else if (ix == DPCHENGPLNRDSNDSN1NDOMAINDATA) return("DpchEngPlnrDsnDsn1NDomainData");
	else if (ix == DPCHENGPLNRDSNDSN1NDOMAINGDDATA) return("DpchEngPlnrDsnDsn1NDomaingdData");
	else if (ix == DPCHENGPLNRDSNDSN1NSTACKDATA) return("DpchEngPlnrDsnDsn1NStackData");
	else if (ix == DPCHENGPLNRDSNHEADBARDATA) return("DpchEngPlnrDsnHeadbarData");
	else if (ix == DPCHENGPLNRDSNHK1NARCGUIDEDATA) return("DpchEngPlnrDsnHk1NArcguideData");
	else if (ix == DPCHENGPLNRDSNHK1NLAYERDATA) return("DpchEngPlnrDsnHk1NLayerData");
	else if (ix == DPCHENGPLNRDSNHK1NLEVELDATA) return("DpchEngPlnrDsnHk1NLevelData");
	else if (ix == DPCHENGPLNRDSNHK1NLINEGUIDEDATA) return("DpchEngPlnrDsnHk1NLineguideData");
	else if (ix == DPCHENGPLNRDSNHK1NSTRUCTUREDATA) return("DpchEngPlnrDsnHk1NStructureData");
	else if (ix == DPCHENGPLNRDSNHK1NVERTEXDATA) return("DpchEngPlnrDsnHk1NVertexData");
	else if (ix == DPCHENGPLNRDSNLISTDATA) return("DpchEngPlnrDsnListData");
	else if (ix == DPCHENGPLNRDSNMOD1NDESIGNDATA) return("DpchEngPlnrDsnMod1NDesignData");
	else if (ix == DPCHENGPLNRDSNPREDATA) return("DpchEngPlnrDsnPreData");
	else if (ix == DPCHENGPLNRDSNRECDATA) return("DpchEngPlnrDsnRecData");
	else if (ix == DPCHENGPLNRDSNVIEWXYDATA) return("DpchEngPlnrDsnViewxyData");
	else if (ix == DPCHENGPLNRDSNVIEWZDATA) return("DpchEngPlnrDsnViewzData");
	else if (ix == DPCHENGPLNRDTPAPARDATA) return("DpchEngPlnrDtpAParData");
	else if (ix == DPCHENGPLNRDTPDATA) return("DpchEngPlnrDtpData");
	else if (ix == DPCHENGPLNRDTPDETAILDATA) return("DpchEngPlnrDtpDetailData");
	else if (ix == DPCHENGPLNRDTPHEADBARDATA) return("DpchEngPlnrDtpHeadbarData");
	else if (ix == DPCHENGPLNRDTPHK1NSTRUCTUREDATA) return("DpchEngPlnrDtpHk1NStructureData");
	else if (ix == DPCHENGPLNRDTPKPARKEYDATA) return("DpchEngPlnrDtpKParKeyData");
	else if (ix == DPCHENGPLNRDTPLISTDATA) return("DpchEngPlnrDtpListData");
	else if (ix == DPCHENGPLNRDTPPREDATA) return("DpchEngPlnrDtpPreData");
	else if (ix == DPCHENGPLNRDTPRECDATA) return("DpchEngPlnrDtpRecData");
	else if (ix == DPCHENGPLNRDTPSUP1NDEVICEDATA) return("DpchEngPlnrDtpSup1NDeviceData");
	else if (ix == DPCHENGPLNRDTPTPL1NDEVICEDATA) return("DpchEngPlnrDtpTpl1NDeviceData");
	else if (ix == DPCHENGPLNRDTPVIEWDATA) return("DpchEngPlnrDtpViewData");
	else if (ix == DPCHENGPLNRDVCAPARDATA) return("DpchEngPlnrDvcAParData");
	else if (ix == DPCHENGPLNRDVCDATA) return("DpchEngPlnrDvcData");
	else if (ix == DPCHENGPLNRDVCDETAILDATA) return("DpchEngPlnrDvcDetailData");
	else if (ix == DPCHENGPLNRDVCHEADBARDATA) return("DpchEngPlnrDvcHeadbarData");
	else if (ix == DPCHENGPLNRDVCHK1NARCGUIDEDATA) return("DpchEngPlnrDvcHk1NArcguideData");
	else if (ix == DPCHENGPLNRDVCHK1NLINEGUIDEDATA) return("DpchEngPlnrDvcHk1NLineguideData");
	else if (ix == DPCHENGPLNRDVCHK1NSTRUCTUREDATA) return("DpchEngPlnrDvcHk1NStructureData");
	else if (ix == DPCHENGPLNRDVCHK1NVERTEXDATA) return("DpchEngPlnrDvcHk1NVertexData");
	else if (ix == DPCHENGPLNRDVCLISTDATA) return("DpchEngPlnrDvcListData");
	else if (ix == DPCHENGPLNRDVCPREDATA) return("DpchEngPlnrDvcPreData");
	else if (ix == DPCHENGPLNRDVCRECDATA) return("DpchEngPlnrDvcRecData");
	else if (ix == DPCHENGPLNRDVCSUP1NDEVICEDATA) return("DpchEngPlnrDvcSup1NDeviceData");
	else if (ix == DPCHENGPLNRDVCVIEWDATA) return("DpchEngPlnrDvcViewData");
	else if (ix == DPCHENGPLNRFILDATA) return("DpchEngPlnrFilData");
	else if (ix == DPCHENGPLNRFILDETAILDATA) return("DpchEngPlnrFilDetailData");
	else if (ix == DPCHENGPLNRFILHEADBARDATA) return("DpchEngPlnrFilHeadbarData");
	else if (ix == DPCHENGPLNRFILLISTDATA) return("DpchEngPlnrFilListData");
	else if (ix == DPCHENGPLNRFILMNCALCDATA) return("DpchEngPlnrFilMNCalcData");
	else if (ix == DPCHENGPLNRFILRECDATA) return("DpchEngPlnrFilRecData");
	else if (ix == DPCHENGPLNRLYR1NBLOCKDATA) return("DpchEngPlnrLyr1NBlockData");
	else if (ix == DPCHENGPLNRLYR1NRETICLEDATA) return("DpchEngPlnrLyr1NReticleData");
	else if (ix == DPCHENGPLNRLYRDATA) return("DpchEngPlnrLyrData");
	else if (ix == DPCHENGPLNRLYRDETAILDATA) return("DpchEngPlnrLyrDetailData");
	else if (ix == DPCHENGPLNRLYRHEADBARDATA) return("DpchEngPlnrLyrHeadbarData");
	else if (ix == DPCHENGPLNRLYRLISTDATA) return("DpchEngPlnrLyrListData");
	else if (ix == DPCHENGPLNRLYRMNSTRUCTUREDATA) return("DpchEngPlnrLyrMNStructureData");
	else if (ix == DPCHENGPLNRLYRRECDATA) return("DpchEngPlnrLyrRecData");
	else if (ix == DPCHENGPLNRMAT1NLAYERDATA) return("DpchEngPlnrMat1NLayerData");
	else if (ix == DPCHENGPLNRMATAPARDATA) return("DpchEngPlnrMatAParData");
	else if (ix == DPCHENGPLNRMATDATA) return("DpchEngPlnrMatData");
	else if (ix == DPCHENGPLNRMATDETAILDATA) return("DpchEngPlnrMatDetailData");
	else if (ix == DPCHENGPLNRMATHEADBARDATA) return("DpchEngPlnrMatHeadbarData");
	else if (ix == DPCHENGPLNRMATLISTDATA) return("DpchEngPlnrMatListData");
	else if (ix == DPCHENGPLNRMATMOD1NMATERIALDATA) return("DpchEngPlnrMatMod1NMaterialData");
	else if (ix == DPCHENGPLNRMATRECDATA) return("DpchEngPlnrMatRecData");
	else if (ix == DPCHENGPLNRMATREF1NFILEDATA) return("DpchEngPlnrMatRef1NFileData");
	else if (ix == DPCHENGPLNRNAVADMINDATA) return("DpchEngPlnrNavAdminData");
	else if (ix == DPCHENGPLNRNAVCALCDATA) return("DpchEngPlnrNavCalcData");
	else if (ix == DPCHENGPLNRNAVDATA) return("DpchEngPlnrNavData");
	else if (ix == DPCHENGPLNRNAVDESIGNDATA) return("DpchEngPlnrNavDesignData");
	else if (ix == DPCHENGPLNRNAVGLOBALDATA) return("DpchEngPlnrNavGlobalData");
	else if (ix == DPCHENGPLNRNAVHEADBARDATA) return("DpchEngPlnrNavHeadbarData");
	else if (ix == DPCHENGPLNRNAVLAYOUTDATA) return("DpchEngPlnrNavLayoutData");
	else if (ix == DPCHENGPLNRNAVPREDATA) return("DpchEngPlnrNavPreData");
	else if (ix == DPCHENGPLNRPRJ1NCALCDATA) return("DpchEngPlnrPrj1NCalcData");
	else if (ix == DPCHENGPLNRPRJ1NDESIGNDATA) return("DpchEngPlnrPrj1NDesignData");
	else if (ix == DPCHENGPLNRPRJDATA) return("DpchEngPlnrPrjData");
	else if (ix == DPCHENGPLNRPRJDETAILDATA) return("DpchEngPlnrPrjDetailData");
	else if (ix == DPCHENGPLNRPRJHEADBARDATA) return("DpchEngPlnrPrjHeadbarData");
	else if (ix == DPCHENGPLNRPRJLISTDATA) return("DpchEngPlnrPrjListData");
	else if (ix == DPCHENGPLNRPRJMNTAPEOUTDATA) return("DpchEngPlnrPrjMNTapeoutData");
	else if (ix == DPCHENGPLNRPRJRECDATA) return("DpchEngPlnrPrjRecData");
	else if (ix == DPCHENGPLNRPRSADETAILDATA) return("DpchEngPlnrPrsADetailData");
	else if (ix == DPCHENGPLNRPRSDATA) return("DpchEngPlnrPrsData");
	else if (ix == DPCHENGPLNRPRSDETAILDATA) return("DpchEngPlnrPrsDetailData");
	else if (ix == DPCHENGPLNRPRSHEADBARDATA) return("DpchEngPlnrPrsHeadbarData");
	else if (ix == DPCHENGPLNRPRSLISTDATA) return("DpchEngPlnrPrsListData");
	else if (ix == DPCHENGPLNRPRSRECDATA) return("DpchEngPlnrPrsRecData");
	else if (ix == DPCHENGPLNRRTCDATA) return("DpchEngPlnrRtcData");
	else if (ix == DPCHENGPLNRRTCDETAILDATA) return("DpchEngPlnrRtcDetailData");
	else if (ix == DPCHENGPLNRRTCHEADBARDATA) return("DpchEngPlnrRtcHeadbarData");
	else if (ix == DPCHENGPLNRRTCLISTDATA) return("DpchEngPlnrRtcListData");
	else if (ix == DPCHENGPLNRRTCRECDATA) return("DpchEngPlnrRtcRecData");
	else if (ix == DPCHENGPLNRSRU1NBLOCKDATA) return("DpchEngPlnrSru1NBlockData");
	else if (ix == DPCHENGPLNRSRUDATA) return("DpchEngPlnrSruData");
	else if (ix == DPCHENGPLNRSRUDETAILDATA) return("DpchEngPlnrSruDetailData");
	else if (ix == DPCHENGPLNRSRUHEADBARDATA) return("DpchEngPlnrSruHeadbarData");
	else if (ix == DPCHENGPLNRSRULISTDATA) return("DpchEngPlnrSruListData");
	else if (ix == DPCHENGPLNRSRUMNLAYERDATA) return("DpchEngPlnrSruMNLayerData");
	else if (ix == DPCHENGPLNRSRUMNSTACKDATA) return("DpchEngPlnrSruMNStackData");
	else if (ix == DPCHENGPLNRSRURECDATA) return("DpchEngPlnrSruRecData");
	else if (ix == DPCHENGPLNRSRUSRU1NFACEDATA) return("DpchEngPlnrSruSru1NFaceData");
	else if (ix == DPCHENGPLNRSTKDATA) return("DpchEngPlnrStkData");
	else if (ix == DPCHENGPLNRSTKDETAILDATA) return("DpchEngPlnrStkDetailData");
	else if (ix == DPCHENGPLNRSTKHEADBARDATA) return("DpchEngPlnrStkHeadbarData");
	else if (ix == DPCHENGPLNRSTKHK1NLAYERDATA) return("DpchEngPlnrStkHk1NLayerData");
	else if (ix == DPCHENGPLNRSTKHK1NLEVELDATA) return("DpchEngPlnrStkHk1NLevelData");
	else if (ix == DPCHENGPLNRSTKLISTDATA) return("DpchEngPlnrStkListData");
	else if (ix == DPCHENGPLNRSTKMNSTRUCTUREDATA) return("DpchEngPlnrStkMNStructureData");
	else if (ix == DPCHENGPLNRSTKPREDATA) return("DpchEngPlnrStkPreData");
	else if (ix == DPCHENGPLNRSTKRECDATA) return("DpchEngPlnrStkRecData");
	else if (ix == DPCHENGPLNRSTKVIEWDATA) return("DpchEngPlnrStkViewData");
	else if (ix == DPCHENGPLNRSUSPEND) return("DpchEngPlnrSuspend");
	else if (ix == DPCHENGPLNRTPO1NARRAYDATA) return("DpchEngPlnrTpo1NArrayData");
	else if (ix == DPCHENGPLNRTPODATA) return("DpchEngPlnrTpoData");
	else if (ix == DPCHENGPLNRTPODETAILDATA) return("DpchEngPlnrTpoDetailData");
	else if (ix == DPCHENGPLNRTPOFLOORPLANDATA) return("DpchEngPlnrTpoFloorplanData");
	else if (ix == DPCHENGPLNRTPOHEADBARDATA) return("DpchEngPlnrTpoHeadbarData");
	else if (ix == DPCHENGPLNRTPOHK1NRETICLEDATA) return("DpchEngPlnrTpoHk1NReticleData");
	else if (ix == DPCHENGPLNRTPOLISTDATA) return("DpchEngPlnrTpoListData");
	else if (ix == DPCHENGPLNRTPOMNPROJECTDATA) return("DpchEngPlnrTpoMNProjectData");
	else if (ix == DPCHENGPLNRTPORECDATA) return("DpchEngPlnrTpoRecData");
	else if (ix == DPCHENGPLNRUSGAACCESSDATA) return("DpchEngPlnrUsgAAccessData");
	else if (ix == DPCHENGPLNRUSGDATA) return("DpchEngPlnrUsgData");
	else if (ix == DPCHENGPLNRUSGDETAILDATA) return("DpchEngPlnrUsgDetailData");
	else if (ix == DPCHENGPLNRUSGHEADBARDATA) return("DpchEngPlnrUsgHeadbarData");
	else if (ix == DPCHENGPLNRUSGLISTDATA) return("DpchEngPlnrUsgListData");
	else if (ix == DPCHENGPLNRUSGMNUSERDATA) return("DpchEngPlnrUsgMNUserData");
	else if (ix == DPCHENGPLNRUSGRECDATA) return("DpchEngPlnrUsgRecData");
	else if (ix == DPCHENGPLNRUSR1NSESSIONDATA) return("DpchEngPlnrUsr1NSessionData");
	else if (ix == DPCHENGPLNRUSRAACCESSDATA) return("DpchEngPlnrUsrAAccessData");
	else if (ix == DPCHENGPLNRUSRDATA) return("DpchEngPlnrUsrData");
	else if (ix == DPCHENGPLNRUSRDETAILDATA) return("DpchEngPlnrUsrDetailData");
	else if (ix == DPCHENGPLNRUSRHEADBARDATA) return("DpchEngPlnrUsrHeadbarData");
	else if (ix == DPCHENGPLNRUSRLISTDATA) return("DpchEngPlnrUsrListData");
	else if (ix == DPCHENGPLNRUSRMNUSERGROUPDATA) return("DpchEngPlnrUsrMNUsergroupData");
	else if (ix == DPCHENGPLNRUSRRECDATA) return("DpchEngPlnrUsrRecData");
	else if (ix == DPCHENGSESSPLNRDATA) return("DpchEngSessPlnrData");
	else if (ix == DPCHINVPLNR) return("DpchInvPlnr");
	else if (ix == DPCHINVPLNREXPCOLLDEV) return("DpchInvPlnrExpColldev");
	else if (ix == DPCHINVPLNREXPCOLLDSN) return("DpchInvPlnrExpColldsn");
	else if (ix == DPCHINVPLNREXPCOLLSTK) return("DpchInvPlnrExpCollstk");
	else if (ix == DPCHINVPLNREXPCORNER) return("DpchInvPlnrExpCorner");
	else if (ix == DPCHINVPLNREXPCROSS) return("DpchInvPlnrExpCross");
	else if (ix == DPCHINVPLNREXPDIRCOUP) return("DpchInvPlnrExpDircoup");
	else if (ix == DPCHINVPLNREXPDISCRES) return("DpchInvPlnrExpDiscres");
	else if (ix == DPCHINVPLNREXPDOTTEXT) return("DpchInvPlnrExpDottext");
	else if (ix == DPCHINVPLNREXPDSN) return("DpchInvPlnrExpDsn");
	else if (ix == DPCHINVPLNREXPGRATCPL) return("DpchInvPlnrExpGratcpl");
	else if (ix == DPCHINVPLNREXPGRAY) return("DpchInvPlnrExpGray");
	else if (ix == DPCHINVPLNREXPIMAGE) return("DpchInvPlnrExpImage");
	else if (ix == DPCHINVPLNREXPMARKER) return("DpchInvPlnrExpMarker");
	else if (ix == DPCHINVPLNREXPPAD) return("DpchInvPlnrExpPad");
	else if (ix == DPCHINVPLNREXPPHCSQ) return("DpchInvPlnrExpPhcsq");
	else if (ix == DPCHINVPLNREXPPHCSQNEG) return("DpchInvPlnrExpPhcsqneg");
	else if (ix == DPCHINVPLNREXPPHCTRIG) return("DpchInvPlnrExpPhctrig");
	else if (ix == DPCHINVPLNREXPPHCTRIGNEG) return("DpchInvPlnrExpPhctrigneg");
	else if (ix == DPCHINVPLNREXPPHOTDET) return("DpchInvPlnrExpPhotdet");
	else if (ix == DPCHINVPLNREXPPIE) return("DpchInvPlnrExpPie");
	else if (ix == DPCHINVPLNREXPPINOUT) return("DpchInvPlnrExpPinout");
	else if (ix == DPCHINVPLNREXPROICADP) return("DpchInvPlnrExpRoicadp");
	else if (ix == DPCHINVPLNREXPRTRESNEG) return("DpchInvPlnrExpRtresneg");
	else if (ix == DPCHINVPLNREXPSPRING) return("DpchInvPlnrExpSpring");
	else if (ix == DPCHINVPLNREXPSTKPERTPL) return("DpchInvPlnrExpStkpertpl");
	else if (ix == DPCHINVPLNREXPSTKREGFILL) return("DpchInvPlnrExpStkregfill");
	else if (ix == DPCHINVPLNREXPVANDERPAUW) return("DpchInvPlnrExpVanderpauw");
	else if (ix == DPCHINVPLNREXPWG) return("DpchInvPlnrExpWg");
	else if (ix == DPCHINVPLNREXPWGBEND) return("DpchInvPlnrExpWgbend");
	else if (ix == DPCHINVPLNREXPWGBENDNEG) return("DpchInvPlnrExpWgbendneg");
	else if (ix == DPCHINVPLNREXPWGNEG) return("DpchInvPlnrExpWgneg");
	else if (ix == DPCHINVPLNREXPWGSUSP) return("DpchInvPlnrExpWgsusp");
	else if (ix == DPCHINVPLNREXPWGTAP) return("DpchInvPlnrExpWgtap");
	else if (ix == DPCHINVPLNREXPWGTAPNEG) return("DpchInvPlnrExpWgtapneg");
	else if (ix == DPCHINVPLNRMEEPTRF2D) return("DpchInvPlnrMeepTrf2d");
	else if (ix == DPCHINVPLNRMEEPTRF3D) return("DpchInvPlnrMeepTrf3d");
	else if (ix == DPCHINVPLNRPLOTDAT1DGNU) return("DpchInvPlnrPlotDat1dgnu");
	else if (ix == DPCHINVPLNRPLOTDAT1DGNUMULT) return("DpchInvPlnrPlotDat1dgnumult");
	else if (ix == DPCHINVPLNRPLOTDEVSVG) return("DpchInvPlnrPlotDevsvg");
	else if (ix == DPCHINVPLNRPLOTDOMDAT1DGNU) return("DpchInvPlnrPlotDomdat1dgnu");
	else if (ix == DPCHINVPLNRPLOTDOMDAT2DGNU) return("DpchInvPlnrPlotDomdat2dgnu");
	else if (ix == DPCHINVPLNRPLOTDOMDAT2DPNG) return("DpchInvPlnrPlotDomdat2dpng");
	else if (ix == DPCHINVPLNRPLOTDOMDAT2DVID) return("DpchInvPlnrPlotDomdat2dvid");
	else if (ix == DPCHINVPLNRPLOTDOMZCSSVG) return("DpchInvPlnrPlotDomzcssvg");
	else if (ix == DPCHINVPLNRPLOTDSNXYSVG) return("DpchInvPlnrPlotDsnxysvg");
	else if (ix == DPCHINVPLNRPLOTDSNZSVG) return("DpchInvPlnrPlotDsnzsvg");
	else if (ix == DPCHINVPLNRPLOTSTKSVG) return("DpchInvPlnrPlotStksvg");
	else if (ix == DPCHINVPLNRPLOTTPOSVG) return("DpchInvPlnrPlotTposvg");
	else if (ix == DPCHINVPLNRPLOTTPOTXT) return("DpchInvPlnrPlotTpotxt");
	else if (ix == DPCHINVPLNRRASTCUB) return("DpchInvPlnrRastCub");
	else if (ix == DPCHINVPLNRRASTXYBOX) return("DpchInvPlnrRastXybox");
	else if (ix == DPCHINVPLNRRASTZLINE) return("DpchInvPlnrRastZline");
	else if (ix == DPCHINVPLNRWGMODEFD1D) return("DpchInvPlnrWgmodeFd1d");
	else if (ix == DPCHINVPLNRWGMODEFD2D) return("DpchInvPlnrWgmodeFd2d");
	else if (ix == DPCHINVPLNRWGMODEFEM1D) return("DpchInvPlnrWgmodeFem1d");
	else if (ix == DPCHINVPLNRWGMODEFEM2D) return("DpchInvPlnrWgmodeFem2d");
	else if (ix == DPCHPLNRDACK) return("DpchPlnrdAck");
	else if (ix == DPCHPLNRDQUIT) return("DpchPlnrdQuit");
	else if (ix == DPCHPLNRDREG) return("DpchPlnrdReg");
	else if (ix == DPCHPLNROPDREG) return("DpchPlnropdReg");
	else if (ix == DPCHPLNROPDUNREG) return("DpchPlnropdUnreg");
	else if (ix == DPCHRETPLNR) return("DpchRetPlnr");
	else if (ix == DPCHRETPLNRPLOTDAT1DGNU) return("DpchRetPlnrPlotDat1dgnu");
	else if (ix == DPCHRETPLNRPLOTDAT1DGNUMULT) return("DpchRetPlnrPlotDat1dgnumult");
	else if (ix == DPCHRETPLNRPLOTDEVSVG) return("DpchRetPlnrPlotDevsvg");
	else if (ix == DPCHRETPLNRPLOTDOMDAT1DGNU) return("DpchRetPlnrPlotDomdat1dgnu");
	else if (ix == DPCHRETPLNRPLOTDOMDAT2DGNU) return("DpchRetPlnrPlotDomdat2dgnu");
	else if (ix == DPCHRETPLNRPLOTDOMDAT2DPNG) return("DpchRetPlnrPlotDomdat2dpng");
	else if (ix == DPCHRETPLNRPLOTDOMDAT2DVID) return("DpchRetPlnrPlotDomdat2dvid");
	else if (ix == DPCHRETPLNRPLOTDOMZCSSVG) return("DpchRetPlnrPlotDomzcssvg");
	else if (ix == DPCHRETPLNRPLOTDSNXYSVG) return("DpchRetPlnrPlotDsnxysvg");
	else if (ix == DPCHRETPLNRPLOTDSNZSVG) return("DpchRetPlnrPlotDsnzsvg");
	else if (ix == DPCHRETPLNRPLOTSTKSVG) return("DpchRetPlnrPlotStksvg");
	else if (ix == DPCHRETPLNRPLOTTPOSVG) return("DpchRetPlnrPlotTposvg");
	else if (ix == DPCHRETPLNRPLOTTPOTXT) return("DpchRetPlnrPlotTpotxt");
	else if (ix == DPCHRETPLNRRASTCUB) return("DpchRetPlnrRastCub");
	else if (ix == DPCHRETPLNRRASTXYBOX) return("DpchRetPlnrRastXybox");
	else if (ix == DPCHRETPLNRRASTZLINE) return("DpchRetPlnrRastZline");
	else if (ix == DPCHRETPLNRWGMODEFD1D) return("DpchRetPlnrWgmodeFd1d");
	else if (ix == DPCHRETPLNRWGMODEFD2D) return("DpchRetPlnrWgmodeFd2d");

	return("");
};


