CREATE DATABASE DbsPlnr;
USE DbsPlnr;

GRANT ALL ON DbsPlnr.* TO 'epsi'@'localhost' IDENTIFIED BY 'f9w8feeh';
GRANT ALL ON DbsPlnr.* TO 'epsi'@'%' IDENTIFIED BY 'f9w8feeh';

DROP TABLE IF EXISTS TblPlnrAccRMUserUniversal;
DROP TABLE IF EXISTS TblPlnrAMArrayEnv;
DROP TABLE IF EXISTS TblPlnrAMCalcEnv;
DROP TABLE IF EXISTS TblPlnrAMCalcPar;
DROP TABLE IF EXISTS TblPlnrAMDevicePar;
DROP TABLE IF EXISTS TblPlnrAMMaterialPar;
DROP TABLE IF EXISTS TblPlnrAMPersonDetail;
DROP TABLE IF EXISTS TblPlnrAMUserAccess;
DROP TABLE IF EXISTS TblPlnrAMUsergroupAccess;
DROP TABLE IF EXISTS TblPlnrAVControlPar;
DROP TABLE IF EXISTS TblPlnrAVKeylistKey;
DROP TABLE IF EXISTS TblPlnrAVValuelistVal;
DROP TABLE IF EXISTS TblPlnrCFile;
DROP TABLE IF EXISTS TblPlnrDevOMDeviceMArcguide;
DROP TABLE IF EXISTS TblPlnrDevOMDeviceMLineguide;
DROP TABLE IF EXISTS TblPlnrDevOMDeviceMVertex;
DROP TABLE IF EXISTS TblPlnrDevORMArcguideMVertex;
DROP TABLE IF EXISTS TblPlnrDevORMLineguideMVertex;
DROP TABLE IF EXISTS TblPlnrHistRMUserUniversal;
DROP TABLE IF EXISTS TblPlnrJAVKeylistKey;
DROP TABLE IF EXISTS TblPlnrJMArcguideR;
DROP TABLE IF EXISTS TblPlnrJMDeviceModtype;
DROP TABLE IF EXISTS TblPlnrJMDomain;
DROP TABLE IF EXISTS TblPlnrJMDomaingd;
DROP TABLE IF EXISTS TblPlnrJMLayer;
DROP TABLE IF EXISTS TblPlnrJMLayerMaterial;
DROP TABLE IF EXISTS TblPlnrJMLevelZ;
DROP TABLE IF EXISTS TblPlnrJMPersonLastname;
DROP TABLE IF EXISTS TblPlnrJMProjectState;
DROP TABLE IF EXISTS TblPlnrJMStackModtype;
DROP TABLE IF EXISTS TblPlnrJMStackN;
DROP TABLE IF EXISTS TblPlnrJMTapeoutState;
DROP TABLE IF EXISTS TblPlnrJMUserState;
DROP TABLE IF EXISTS TblPlnrJMVertex;
DROP TABLE IF EXISTS TblPlnrLRMArcguideMVertex;
DROP TABLE IF EXISTS TblPlnrLRMLineguideMVertex;
DROP TABLE IF EXISTS TblPlnrMArcguide;
DROP TABLE IF EXISTS TblPlnrMArray;
DROP TABLE IF EXISTS TblPlnrMArrayitem;
DROP TABLE IF EXISTS TblPlnrMBlock;
DROP TABLE IF EXISTS TblPlnrMCalc;
DROP TABLE IF EXISTS TblPlnrMCalcitem;
DROP TABLE IF EXISTS TblPlnrMDesign;
DROP TABLE IF EXISTS TblPlnrMDevice;
DROP TABLE IF EXISTS TblPlnrMDomain;
DROP TABLE IF EXISTS TblPlnrMDomaingd;
DROP TABLE IF EXISTS TblPlnrMFace;
DROP TABLE IF EXISTS TblPlnrMFile;
DROP TABLE IF EXISTS TblPlnrMLayer;
DROP TABLE IF EXISTS TblPlnrMLevel;
DROP TABLE IF EXISTS TblPlnrMLineguide;
DROP TABLE IF EXISTS TblPlnrMMaterial;
DROP TABLE IF EXISTS TblPlnrMPerson;
DROP TABLE IF EXISTS TblPlnrMProject;
DROP TABLE IF EXISTS TblPlnrMReticle;
DROP TABLE IF EXISTS TblPlnrMSession;
DROP TABLE IF EXISTS TblPlnrMStack;
DROP TABLE IF EXISTS TblPlnrMStructure;
DROP TABLE IF EXISTS TblPlnrMTapeout;
DROP TABLE IF EXISTS TblPlnrMUser;
DROP TABLE IF EXISTS TblPlnrMUsergroup;
DROP TABLE IF EXISTS TblPlnrMVertex;
DROP TABLE IF EXISTS TblPlnrOMStructureMFace;
DROP TABLE IF EXISTS TblPlnrRMCalcMDomain;
DROP TABLE IF EXISTS TblPlnrRMCalcMFile;
DROP TABLE IF EXISTS TblPlnrRMFaceMVertex;
DROP TABLE IF EXISTS TblPlnrRMLayerMStructure;
DROP TABLE IF EXISTS TblPlnrRMLevelMLevel;
DROP TABLE IF EXISTS TblPlnrRMLineguideMLineguide;
DROP TABLE IF EXISTS TblPlnrRMProjectMTapeout;
DROP TABLE IF EXISTS TblPlnrRMStackMStructure;
DROP TABLE IF EXISTS TblPlnrRMUsergroupUniversal;
DROP TABLE IF EXISTS TblPlnrRMUserMUsergroup;
DROP TABLE IF EXISTS TblPlnrRMVertexMVertex;

DROP TABLE IF EXISTS TblPlnrQAriAMArrayEnv;
DROP TABLE IF EXISTS TblPlnrQAriList;
DROP TABLE IF EXISTS TblPlnrQArr1NArrayitem;
DROP TABLE IF EXISTS TblPlnrQArrAEnv;
DROP TABLE IF EXISTS TblPlnrQArrHk1NReticle;
DROP TABLE IF EXISTS TblPlnrQArrKEnvKey;
DROP TABLE IF EXISTS TblPlnrQArrList;
DROP TABLE IF EXISTS TblPlnrQClc1NMaterial;
DROP TABLE IF EXISTS TblPlnrQClcAEnv;
DROP TABLE IF EXISTS TblPlnrQClcAPar;
DROP TABLE IF EXISTS TblPlnrQClcCal1NCalcitem;
DROP TABLE IF EXISTS TblPlnrQClcList;
DROP TABLE IF EXISTS TblPlnrQClcMNDomain;
DROP TABLE IF EXISTS TblPlnrQClcMNFile;
DROP TABLE IF EXISTS TblPlnrQClcRef1NFile;
DROP TABLE IF EXISTS TblPlnrQClcSup1NCalc;
DROP TABLE IF EXISTS TblPlnrQCliAAMCalcEnv;
DROP TABLE IF EXISTS TblPlnrQCliAAMCalcPar;
DROP TABLE IF EXISTS TblPlnrQCliList;
DROP TABLE IF EXISTS TblPlnrQCliRef1NFile;
DROP TABLE IF EXISTS TblPlnrQCtpAEnv;
DROP TABLE IF EXISTS TblPlnrQCtpAPar;
DROP TABLE IF EXISTS TblPlnrQCtpKCalcdomprp;
DROP TABLE IF EXISTS TblPlnrQCtpKCalcvar;
DROP TABLE IF EXISTS TblPlnrQCtpKEnvKey;
DROP TABLE IF EXISTS TblPlnrQCtpKParCat;
DROP TABLE IF EXISTS TblPlnrQCtpKParProp;
DROP TABLE IF EXISTS TblPlnrQCtpList;
DROP TABLE IF EXISTS TblPlnrQCtpRef1NFile;
DROP TABLE IF EXISTS TblPlnrQCtpSup1NCalc;
DROP TABLE IF EXISTS TblPlnrQCtpTpl1NCalc;
DROP TABLE IF EXISTS TblPlnrQDgdList;
DROP TABLE IF EXISTS TblPlnrQDomList;
DROP TABLE IF EXISTS TblPlnrQDomMNCalc;
DROP TABLE IF EXISTS TblPlnrQDsn1NBlock;
DROP TABLE IF EXISTS TblPlnrQDsn1NReticle;
DROP TABLE IF EXISTS TblPlnrQDsnDrv1NDesign;
DROP TABLE IF EXISTS TblPlnrQDsnDsn1NDevice;
DROP TABLE IF EXISTS TblPlnrQDsnDsn1NDomain;
DROP TABLE IF EXISTS TblPlnrQDsnDsn1NDomaingd;
DROP TABLE IF EXISTS TblPlnrQDsnDsn1NStack;
DROP TABLE IF EXISTS TblPlnrQDsnHk1NArcguide;
DROP TABLE IF EXISTS TblPlnrQDsnHk1NLayer;
DROP TABLE IF EXISTS TblPlnrQDsnHk1NLevel;
DROP TABLE IF EXISTS TblPlnrQDsnHk1NLineguide;
DROP TABLE IF EXISTS TblPlnrQDsnHk1NStructure;
DROP TABLE IF EXISTS TblPlnrQDsnHk1NVertex;
DROP TABLE IF EXISTS TblPlnrQDsnList;
DROP TABLE IF EXISTS TblPlnrQDsnMod1NDesign;
DROP TABLE IF EXISTS TblPlnrQDtpAPar;
DROP TABLE IF EXISTS TblPlnrQDtpHk1NStructure;
DROP TABLE IF EXISTS TblPlnrQDtpKParKey;
DROP TABLE IF EXISTS TblPlnrQDtpList;
DROP TABLE IF EXISTS TblPlnrQDtpSup1NDevice;
DROP TABLE IF EXISTS TblPlnrQDtpTpl1NDevice;
DROP TABLE IF EXISTS TblPlnrQDvcAPar;
DROP TABLE IF EXISTS TblPlnrQDvcHk1NArcguide;
DROP TABLE IF EXISTS TblPlnrQDvcHk1NLineguide;
DROP TABLE IF EXISTS TblPlnrQDvcHk1NStructure;
DROP TABLE IF EXISTS TblPlnrQDvcHk1NVertex;
DROP TABLE IF EXISTS TblPlnrQDvcList;
DROP TABLE IF EXISTS TblPlnrQDvcSup1NDevice;
DROP TABLE IF EXISTS TblPlnrQFilList;
DROP TABLE IF EXISTS TblPlnrQFilMNCalc;
DROP TABLE IF EXISTS TblPlnrQLyr1NBlock;
DROP TABLE IF EXISTS TblPlnrQLyr1NReticle;
DROP TABLE IF EXISTS TblPlnrQLyrList;
DROP TABLE IF EXISTS TblPlnrQLyrMNStructure;
DROP TABLE IF EXISTS TblPlnrQMat1NLayer;
DROP TABLE IF EXISTS TblPlnrQMatAPar;
DROP TABLE IF EXISTS TblPlnrQMatList;
DROP TABLE IF EXISTS TblPlnrQMatMod1NMaterial;
DROP TABLE IF EXISTS TblPlnrQMatRef1NFile;
DROP TABLE IF EXISTS TblPlnrQPreselect;
DROP TABLE IF EXISTS TblPlnrQPrj1NCalc;
DROP TABLE IF EXISTS TblPlnrQPrj1NDesign;
DROP TABLE IF EXISTS TblPlnrQPrjList;
DROP TABLE IF EXISTS TblPlnrQPrjMNTapeout;
DROP TABLE IF EXISTS TblPlnrQPrsADetail;
DROP TABLE IF EXISTS TblPlnrQPrsList;
DROP TABLE IF EXISTS TblPlnrQRtcList;
DROP TABLE IF EXISTS TblPlnrQSelect;
DROP TABLE IF EXISTS TblPlnrQSru1NBlock;
DROP TABLE IF EXISTS TblPlnrQSruList;
DROP TABLE IF EXISTS TblPlnrQSruMNLayer;
DROP TABLE IF EXISTS TblPlnrQSruMNStack;
DROP TABLE IF EXISTS TblPlnrQSruSru1NFace;
DROP TABLE IF EXISTS TblPlnrQStkHk1NLayer;
DROP TABLE IF EXISTS TblPlnrQStkHk1NLevel;
DROP TABLE IF EXISTS TblPlnrQStkList;
DROP TABLE IF EXISTS TblPlnrQStkMNStructure;
DROP TABLE IF EXISTS TblPlnrQTpo1NArray;
DROP TABLE IF EXISTS TblPlnrQTpoHk1NReticle;
DROP TABLE IF EXISTS TblPlnrQTpoList;
DROP TABLE IF EXISTS TblPlnrQTpoMNProject;
DROP TABLE IF EXISTS TblPlnrQUsgAAccess;
DROP TABLE IF EXISTS TblPlnrQUsgList;
DROP TABLE IF EXISTS TblPlnrQUsgMNUser;
DROP TABLE IF EXISTS TblPlnrQUsr1NSession;
DROP TABLE IF EXISTS TblPlnrQUsrAAccess;
DROP TABLE IF EXISTS TblPlnrQUsrList;
DROP TABLE IF EXISTS TblPlnrQUsrMNUsergroup;

CREATE TABLE TblPlnrAccRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMUser BIGINT UNSIGNED,
	unvIxPlnrVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixPlnrVAccess INT UNSIGNED,
	INDEX (refPlnrMUser),
	INDEX (unvIxPlnrVMaintable),
	INDEX (unvUref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAMArrayEnv(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMArray BIGINT UNSIGNED,
	x1RefPlnrMArrayitem BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	Val VARCHAR(255),
	INDEX (refPlnrMArray),
	INDEX (x1RefPlnrMArrayitem),
	INDEX (x2SrefKKey)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAMCalcEnv(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMCalc BIGINT UNSIGNED,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	Val VARCHAR(255),
	INDEX (refPlnrMCalc),
	INDEX (x1RefPlnrMCalcitem),
	INDEX (x2SrefKKey)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAMCalcPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMCalc BIGINT UNSIGNED,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	x2SrefKCat VARCHAR(50),
	x3SrefKProp VARCHAR(50),
	Val VARCHAR(255),
	INDEX (refPlnrMCalc),
	INDEX (x1RefPlnrMCalcitem),
	INDEX (x2SrefKCat),
	INDEX (x3SrefKProp)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAMDevicePar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMDevice BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	refPlnrMFile BIGINT UNSIGNED,
	Val VARCHAR(255),
	INDEX (refPlnrMDevice),
	INDEX (x1RefPlnrMDesign),
	INDEX (x2SrefKKey)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAMMaterialPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMMaterial BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	x2SrefKCat VARCHAR(50),
	x3SrefKProp VARCHAR(50),
	refPlnrMFile BIGINT UNSIGNED,
	Val VARCHAR(255),
	Comment TEXT,
	INDEX (refPlnrMMaterial),
	INDEX (x1RefPlnrMDesign),
	INDEX (x2SrefKCat),
	INDEX (x3SrefKProp)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAMPersonDetail(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMPerson BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(255),
	INDEX (refPlnrMPerson),
	INDEX (x1SrefKType)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAMUserAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMUser BIGINT UNSIGNED,
	x1IxPlnrVCard INT UNSIGNED,
	ixPlnrWUiaccess INT UNSIGNED,
	INDEX (refPlnrMUser),
	INDEX (x1IxPlnrVCard)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAMUsergroupAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMUsergroup BIGINT UNSIGNED,
	x1IxPlnrVCard INT UNSIGNED,
	ixPlnrWUiaccess INT UNSIGNED,
	INDEX (refPlnrMUsergroup),
	INDEX (x1IxPlnrVCard)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAVControlPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixPlnrVControl INT UNSIGNED,
	x1RefPlnrMUser BIGINT UNSIGNED,
	x2IxPlnrVLocale INT UNSIGNED,
	Par VARCHAR(255),
	Val VARCHAR(255),
	INDEX (ixPlnrVControl),
	INDEX (x1RefPlnrMUser),
	INDEX (x2IxPlnrVLocale)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	klsIxPlnrVKeylist INT UNSIGNED,
	klsNum INT UNSIGNED,
	x1IxPlnrVMaintable INT UNSIGNED,
	x1Uref BIGINT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (klsNum),
	INDEX (x1IxPlnrVMaintable),
	INDEX (x1Uref),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrAVValuelistVal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	vlsIxPlnrVValuelist INT UNSIGNED,
	vlsNum INT UNSIGNED,
	x1IxPlnrVLocale INT UNSIGNED,
	Val VARCHAR(255),
	INDEX (vlsIxPlnrVValuelist),
	INDEX (vlsNum),
	INDEX (x1IxPlnrVLocale)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrCFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblPlnrDevOMDeviceMArcguide(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMDevice BIGINT UNSIGNED,
	x1RefPlnrMDevice BIGINT UNSIGNED,
	ixPlnrVLop INT UNSIGNED,
	pr1RefM BIGINT UNSIGNED,
	INDEX (refPlnrMDevice),
	INDEX (x1RefPlnrMDevice),
	INDEX (ixPlnrVLop),
	INDEX (pr1RefM)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrDevOMDeviceMLineguide(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMDevice BIGINT UNSIGNED,
	x1RefPlnrMDevice BIGINT UNSIGNED,
	ixPlnrVLop INT UNSIGNED,
	pr1RefM BIGINT UNSIGNED,
	INDEX (refPlnrMDevice),
	INDEX (x1RefPlnrMDevice),
	INDEX (ixPlnrVLop),
	INDEX (pr1RefM)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrDevOMDeviceMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMDevice BIGINT UNSIGNED,
	x1RefPlnrMDevice BIGINT UNSIGNED,
	ixPlnrVLop INT UNSIGNED,
	pr1RefM BIGINT UNSIGNED,
	INDEX (refPlnrMDevice),
	INDEX (x1RefPlnrMDevice),
	INDEX (ixPlnrVLop),
	INDEX (pr1RefM)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrDevORMArcguideMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMArcguide BIGINT UNSIGNED,
	x1RefPlnrMDevice BIGINT UNSIGNED,
	ixPlnrVLop INT UNSIGNED,
	pr1RefLR BIGINT UNSIGNED,
	INDEX (refPlnrMArcguide),
	INDEX (x1RefPlnrMDevice),
	INDEX (ixPlnrVLop),
	INDEX (pr1RefLR)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrDevORMLineguideMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMLineguide BIGINT UNSIGNED,
	x1RefPlnrMDevice BIGINT UNSIGNED,
	ixPlnrVLop INT UNSIGNED,
	pr1RefLR BIGINT UNSIGNED,
	INDEX (refPlnrMLineguide),
	INDEX (x1RefPlnrMDevice),
	INDEX (ixPlnrVLop),
	INDEX (pr1RefLR)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrHistRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMUser BIGINT UNSIGNED,
	unvIxPlnrVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixPlnrVCard INT UNSIGNED,
	ixPlnrVPreset INT UNSIGNED,
	preIxPlnrVMaintable INT UNSIGNED,
	preUref BIGINT UNSIGNED,
	start INT UNSIGNED,
	INDEX (refPlnrMUser),
	INDEX (unvIxPlnrVMaintable),
	INDEX (unvUref),
	INDEX (ixPlnrVCard),
	INDEX (ixPlnrVPreset),
	INDEX (preIxPlnrVMaintable),
	INDEX (preUref),
	INDEX (start)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrAVKeylistKey BIGINT UNSIGNED,
	x1IxPlnrVLocale INT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (refPlnrAVKeylistKey),
	INDEX (x1IxPlnrVLocale)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMArcguideR(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMArcguide BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	r DOUBLE,
	INDEX (refPlnrMArcguide),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMDeviceModtype(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMDevice BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	ixVModtype INT UNSIGNED,
	INDEX (refPlnrMDevice),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMDomain(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMDomain BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	dx VARCHAR(30),
	dy VARCHAR(30),
	dxy VARCHAR(30),
	dz VARCHAR(30),
	INDEX (refPlnrMDomain),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMDomaingd(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMDomaingd BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	d VARCHAR(30),
	dphi VARCHAR(30),
	INDEX (refPlnrMDomaingd),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMLayer(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMLayer BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	t VARCHAR(30),
	ML VARCHAR(30),
	INDEX (refPlnrMLayer),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMLayerMaterial(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMLayer BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	refPlnrMMaterial BIGINT UNSIGNED,
	INDEX (refPlnrMLayer),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMLevelZ(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMLevel BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	z DOUBLE,
	INDEX (refPlnrMLevel),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMPersonLastname(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMPerson BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	Lastname VARCHAR(50),
	INDEX (refPlnrMPerson),
	INDEX (x1Startd),
	INDEX (Lastname)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMProjectState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMProject BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refPlnrMProject),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMStackModtype(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMStack BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	ixVModtype INT UNSIGNED,
	INDEX (refPlnrMStack),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMStackN(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMStack BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	N VARCHAR(30),
	INDEX (refPlnrMStack),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMTapeoutState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMTapeout BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refPlnrMTapeout),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMUserState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMUser BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refPlnrMUser),
	INDEX (x1Startd)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrJMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMVertex BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	x DOUBLE,
	y DOUBLE,
	INDEX (refPlnrMVertex),
	INDEX (x1RefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrLRMArcguideMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	agdIxPlnrVLat INT UNSIGNED,
	agdRefPlnrMArcguide BIGINT UNSIGNED,
	agdNum INT UNSIGNED,
	refPlnrMVertex BIGINT UNSIGNED,
	INDEX (agdIxPlnrVLat),
	INDEX (agdRefPlnrMArcguide),
	INDEX (agdNum),
	INDEX (refPlnrMVertex)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrLRMLineguideMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	lgdIxPlnrVLat INT UNSIGNED,
	lgdRefPlnrMLineguide BIGINT UNSIGNED,
	lgdNum INT UNSIGNED,
	refPlnrMVertex BIGINT UNSIGNED,
	INDEX (lgdIxPlnrVLat),
	INDEX (lgdRefPlnrMLineguide),
	INDEX (lgdNum),
	INDEX (refPlnrMVertex)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMArcguide(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	devRefPlnrMArcguide BIGINT UNSIGNED,
	hkIxPlnrVLat INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ctrRefPlnrMVertex BIGINT UNSIGNED,
	r DOUBLE,
	INDEX (x1RefPlnrMDesign),
	INDEX (devRefPlnrMArcguide),
	INDEX (hkIxPlnrVLat),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (sref),
	INDEX (ctrRefPlnrMVertex)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMArray(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMTapeout BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	sref VARCHAR(50),
	I SMALLINT UNSIGNED,
	J SMALLINT UNSIGNED,
	di DOUBLE,
	dj DOUBLE,
	K SMALLINT UNSIGNED,
	L SMALLINT UNSIGNED,
	dk DOUBLE,
	dl DOUBLE,
	M SMALLINT UNSIGNED,
	N SMALLINT UNSIGNED,
	dm DOUBLE,
	dn DOUBLE,
	INDEX (refPlnrMTapeout),
	INDEX (refPlnrMDesign),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMArrayitem(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMArray BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	i SMALLINT UNSIGNED,
	j SMALLINT UNSIGNED,
	k SMALLINT UNSIGNED,
	l SMALLINT UNSIGNED,
	m SMALLINT UNSIGNED,
	n SMALLINT UNSIGNED,
	dx DOUBLE,
	dy DOUBLE,
	INDEX (refPlnrMArray),
	INDEX (refPlnrMDesign),
	INDEX (i),
	INDEX (j),
	INDEX (k),
	INDEX (l),
	INDEX (m),
	INDEX (n)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMBlock(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMDesign BIGINT UNSIGNED,
	refPlnrMStructure BIGINT UNSIGNED,
	refPlnrMLayer BIGINT UNSIGNED,
	INDEX (refPlnrMDesign),
	INDEX (refPlnrMStructure),
	INDEX (refPlnrMLayer)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMCalc(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refPlnrMProject BIGINT UNSIGNED,
	ixVDim INT UNSIGNED,
	tplRefPlnrMCalc BIGINT UNSIGNED,
	supRefPlnrMCalc BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	Title VARCHAR(50),
	start INT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refPlnrMProject),
	INDEX (ixVDim),
	INDEX (tplRefPlnrMCalc),
	INDEX (supRefPlnrMCalc),
	INDEX (refPlnrMDesign),
	INDEX (Title),
	INDEX (start)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMCalcitem(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	calRefPlnrMCalc BIGINT UNSIGNED,
	calNum INT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	Title VARCHAR(50),
	INDEX (calRefPlnrMCalc),
	INDEX (calNum),
	INDEX (refPlnrMDesign),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMDesign(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixVBasetype INT UNSIGNED,
	ixVDim INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refPlnrMProject BIGINT UNSIGNED,
	ixWModtype INT UNSIGNED,
	modRefPlnrMDesign BIGINT UNSIGNED,
	drvRefPlnrMDesign BIGINT UNSIGNED,
	Title VARCHAR(50),
	Major SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (ixVBasetype),
	INDEX (ixVDim),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (refPlnrMProject),
	INDEX (ixWModtype),
	INDEX (modRefPlnrMDesign),
	INDEX (drvRefPlnrMDesign)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMDevice(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	dsnRefPlnrMDesign BIGINT UNSIGNED,
	dsnNum INT UNSIGNED,
	supRefPlnrMDevice BIGINT UNSIGNED,
	supNum INT UNSIGNED,
	tplRefPlnrMDevice BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVModtype INT UNSIGNED,
	ixVAligntype INT UNSIGNED,
	av1SrefPlnrMVertex VARCHAR(50),
	pav1SrefPlnrMVertex VARCHAR(50),
	av2SrefPlnrMVertex VARCHAR(50),
	pav2SrefPlnrMVertex VARCHAR(50),
	x DOUBLE,
	y DOUBLE,
	phi DOUBLE,
	Comment TEXT,
	INDEX (dsnRefPlnrMDesign),
	INDEX (dsnNum),
	INDEX (supRefPlnrMDevice),
	INDEX (supNum),
	INDEX (tplRefPlnrMDevice),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMDomain(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	dsnRefPlnrMDesign BIGINT UNSIGNED,
	dsnNum INT UNSIGNED,
	sref VARCHAR(50),
	flrSrefPlnrMLevel VARCHAR(50),
	ceilSrefPlnrMLevel VARCHAR(50),
	vtx1SrefPlnrMVertex VARCHAR(50),
	lgd1SrefPlnrMLineguide VARCHAR(50),
	vtx2SrefPlnrMVertex VARCHAR(50),
	lgd2SrefPlnrMLineguide VARCHAR(50),
	vtx3SrefPlnrMVertex VARCHAR(50),
	lgd3SrefPlnrMLineguide VARCHAR(50),
	vtx4SrefPlnrMVertex VARCHAR(50),
	lgd4SrefPlnrMLineguide VARCHAR(50),
	dx VARCHAR(30),
	dy VARCHAR(30),
	dxy VARCHAR(30),
	dz VARCHAR(30),
	INDEX (ixVBasetype),
	INDEX (dsnRefPlnrMDesign),
	INDEX (dsnNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMDomaingd(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	dsnRefPlnrMDesign BIGINT UNSIGNED,
	dsnNum INT UNSIGNED,
	sref VARCHAR(50),
	srefPlnrMLevel VARCHAR(50),
	av1SrefPlnrMVertex VARCHAR(50),
	av2SrefPlnrMVertex VARCHAR(50),
	al1SrefPlnrMLineguide VARCHAR(50),
	al2SrefPlnrMLineguide VARCHAR(50),
	srefPlnrMArcguide VARCHAR(50),
	d VARCHAR(30),
	dphi VARCHAR(30),
	INDEX (ixVBasetype),
	INDEX (dsnRefPlnrMDesign),
	INDEX (dsnNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMFace(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	devRefPlnrMFace BIGINT UNSIGNED,
	sruIxPlnrVLat INT UNSIGNED,
	sruRefPlnrMStructure BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (x1RefPlnrMDesign),
	INDEX (devRefPlnrMFace),
	INDEX (sruIxPlnrVLat),
	INDEX (sruRefPlnrMStructure),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refPlnrCFile BIGINT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	Archived INT UNSIGNED,
	Filename VARCHAR(50),
	Archivename VARCHAR(30),
	srefKMimetype VARCHAR(50),
	Size INT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refPlnrCFile),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (Filename)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMLayer(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	refPlnrMMaterial BIGINT UNSIGNED,
	ixVTtype INT UNSIGNED,
	sref VARCHAR(50),
	flrRefPlnrMLevel BIGINT UNSIGNED,
	ctrRefPlnrMLevel BIGINT UNSIGNED,
	ceilRefPlnrMLevel BIGINT UNSIGNED,
	t VARCHAR(30),
	ML VARCHAR(30),
	INDEX (x1RefPlnrMDesign),
	INDEX (ixVBasetype),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (hkNum),
	INDEX (refPlnrMMaterial),
	INDEX (ixVTtype),
	INDEX (sref),
	INDEX (flrRefPlnrMLevel),
	INDEX (ctrRefPlnrMLevel),
	INDEX (ceilRefPlnrMLevel)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMLevel(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	sref VARCHAR(50),
	z DOUBLE,
	INDEX (x1RefPlnrMDesign),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (sref),
	INDEX (z)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMLineguide(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	hkIxPlnrVLat INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (x1RefPlnrMDesign),
	INDEX (hkIxPlnrVLat),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMMaterial(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixVBasetype INT UNSIGNED,
	refPlnrMCalc BIGINT UNSIGNED,
	modRefPlnrMMaterial BIGINT UNSIGNED,
	modLvl SMALLINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	INDEX (grp),
	INDEX (own),
	INDEX (ixVBasetype),
	INDEX (refPlnrMCalc),
	INDEX (modRefPlnrMMaterial),
	INDEX (modLvl),
	INDEX (sref),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMPerson(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixWDerivate INT UNSIGNED,
	ixVSex INT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	refJLastname BIGINT UNSIGNED,
	Lastname VARCHAR(50),
	telRefADetail BIGINT UNSIGNED,
	Tel VARCHAR(255),
	emlRefADetail BIGINT UNSIGNED,
	Eml VARCHAR(255),
	Salutation VARCHAR(100),
	INDEX (grp),
	INDEX (own),
	INDEX (ixWDerivate),
	INDEX (Lastname)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMProject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Title VARCHAR(50),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMReticle(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	refPlnrMLayer BIGINT UNSIGNED,
	sref VARCHAR(50),
	x0 DOUBLE,
	y0 DOUBLE,
	phi DOUBLE,
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (refPlnrMDesign),
	INDEX (refPlnrMLayer),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMSession(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMUser BIGINT UNSIGNED,
	start INT UNSIGNED,
	stop INT UNSIGNED,
	Ip VARCHAR(30),
	INDEX (refPlnrMUser),
	INDEX (start)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMStack(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	dsnRefPlnrMDesign BIGINT UNSIGNED,
	dsnNum INT UNSIGNED,
	sref VARCHAR(50),
	ixVModtype INT UNSIGNED,
	ixVFlrAligntype INT UNSIGNED,
	flrSrefPlnrMLevel VARCHAR(50),
	zFlr DOUBLE,
	ixVCeilAligntype INT UNSIGNED,
	ceilSrefPlnrMLevel VARCHAR(50),
	zCeil DOUBLE,
	srefsPlnrMLayer VARCHAR(255),
	N VARCHAR(30),
	INDEX (ixVBasetype),
	INDEX (dsnRefPlnrMDesign),
	INDEX (dsnNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMStructure(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	sref VARCHAR(50),
	x0 DOUBLE,
	x1 DOUBLE,
	y0 DOUBLE,
	y1 DOUBLE,
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMTapeout(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixVBasetype INT UNSIGNED,
	Title VARCHAR(50),
	Major SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Hflip TINYINT,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (ixVBasetype),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMUser(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refRUsergroup BIGINT UNSIGNED,
	refPlnrMUsergroup BIGINT UNSIGNED,
	refPlnrMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixPlnrVLocale INT UNSIGNED,
	ixPlnrVUserlevel INT UNSIGNED,
	Password VARCHAR(30),
	INDEX (grp),
	INDEX (own),
	INDEX (refPlnrMUsergroup),
	INDEX (refPlnrMPerson),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	hkIxPlnrVLat INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	sref VARCHAR(50),
	x DOUBLE,
	y DOUBLE,
	INDEX (x1RefPlnrMDesign),
	INDEX (hkIxPlnrVLat),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrOMStructureMFace(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMStructure BIGINT UNSIGNED,
	x1RefPlnrMDevice BIGINT UNSIGNED,
	ixPlnrVLop INT UNSIGNED,
	pr1RefM BIGINT UNSIGNED,
	INDEX (refPlnrMStructure),
	INDEX (x1RefPlnrMDevice),
	INDEX (ixPlnrVLop),
	INDEX (pr1RefM)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMCalcMDomain(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMCalc BIGINT UNSIGNED,
	refPlnrMDomain BIGINT UNSIGNED,
	srefPlnrKCalcdomprp VARCHAR(50),
	INDEX (refPlnrMCalc),
	INDEX (refPlnrMDomain)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMCalcMFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	refPlnrMCalc BIGINT UNSIGNED,
	refPlnrMFile BIGINT UNSIGNED,
	ixVIo INT UNSIGNED,
	INDEX (x1RefPlnrMCalcitem),
	INDEX (refPlnrMCalc),
	INDEX (refPlnrMFile)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMFaceMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	fceRefPlnrMFace BIGINT UNSIGNED,
	fceNum INT UNSIGNED,
	refPlnrMVertex BIGINT UNSIGNED,
	rteIxVTbl INT UNSIGNED,
	rteUref BIGINT UNSIGNED,
	ixVDir INT UNSIGNED,
	INDEX (fceRefPlnrMFace),
	INDEX (fceNum),
	INDEX (refPlnrMVertex),
	INDEX (rteIxVTbl),
	INDEX (rteUref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMLayerMStructure(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMLayer BIGINT UNSIGNED,
	refPlnrMStructure BIGINT UNSIGNED,
	INDEX (refPlnrMLayer),
	INDEX (refPlnrMStructure)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMLevelMLevel(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	stkRefPlnrMLevel BIGINT UNSIGNED,
	dsnRefPlnrMLevel BIGINT UNSIGNED,
	INDEX (stkRefPlnrMLevel),
	INDEX (dsnRefPlnrMLevel)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMLineguideMLineguide(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	devRefPlnrMLineguide BIGINT UNSIGNED,
	dsnRefPlnrMLineguide BIGINT UNSIGNED,
	INDEX (devRefPlnrMLineguide),
	INDEX (dsnRefPlnrMLineguide)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMProjectMTapeout(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMProject BIGINT UNSIGNED,
	refPlnrMTapeout BIGINT UNSIGNED,
	INDEX (refPlnrMProject),
	INDEX (refPlnrMTapeout)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMStackMStructure(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMStack BIGINT UNSIGNED,
	refPlnrMStructure BIGINT UNSIGNED,
	fromSrefPlnrMLayer VARCHAR(50),
	toSrefPlnrMLayer VARCHAR(50),
	INDEX (refPlnrMStack),
	INDEX (refPlnrMStructure)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMUsergroupUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMUsergroup BIGINT UNSIGNED,
	unvIxPlnrVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixPlnrVAccess INT UNSIGNED,
	INDEX (refPlnrMUsergroup),
	INDEX (unvIxPlnrVMaintable),
	INDEX (unvUref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMUserMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refPlnrMUser BIGINT UNSIGNED,
	refPlnrMUsergroup BIGINT UNSIGNED,
	ixPlnrVUserlevel INT UNSIGNED,
	INDEX (refPlnrMUser),
	INDEX (refPlnrMUsergroup)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrRMVertexMVertex(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	devRefPlnrMVertex BIGINT UNSIGNED,
	dsnRefPlnrMVertex BIGINT UNSIGNED,
	INDEX (devRefPlnrMVertex),
	INDEX (dsnRefPlnrMVertex)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQAriAMArrayEnv(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQAriList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	i SMALLINT UNSIGNED,
	j SMALLINT UNSIGNED,
	k SMALLINT UNSIGNED,
	l SMALLINT UNSIGNED,
	m SMALLINT UNSIGNED,
	n SMALLINT UNSIGNED,
	refPlnrMArray BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	dx DOUBLE,
	dy DOUBLE,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQArr1NArrayitem(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQArrAEnv(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMArrayitem BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQArrHk1NReticle(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQArrKEnvKey(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQArrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refPlnrMTapeout BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	I SMALLINT UNSIGNED,
	J SMALLINT UNSIGNED,
	K SMALLINT UNSIGNED,
	L SMALLINT UNSIGNED,
	M SMALLINT UNSIGNED,
	N SMALLINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClc1NMaterial(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClcAEnv(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClcAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	x2SrefKCat VARCHAR(50),
	x3SrefKProp VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClcCal1NCalcitem(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	calNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClcList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(50),
	refPlnrMProject BIGINT UNSIGNED,
	ixVDim INT UNSIGNED,
	tplRefPlnrMCalc BIGINT UNSIGNED,
	supRefPlnrMCalc BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClcMNDomain(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	srefPlnrKCalcdomprp VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClcMNFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	ixVIo INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClcRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQClcSup1NCalc(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCliAAMCalcEnv(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCliAAMCalcPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x2SrefKCat VARCHAR(50),
	x3SrefKProp VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCliList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(50),
	calRefPlnrMCalc BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCliRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpAEnv(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	x2SrefKCat VARCHAR(50),
	x3SrefKProp VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpKCalcdomprp(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpKCalcvar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpKEnvKey(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	sref VARCHAR(50),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpKParCat(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	sref VARCHAR(50),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpKParProp(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(50),
	ixVDim INT UNSIGNED,
	supRefPlnrMCalc BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpSup1NCalc(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQCtpTpl1NCalc(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDgdList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	dsnRefPlnrMDesign BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDomList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	dsnRefPlnrMDesign BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDomMNCalc(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	srefPlnrKCalcdomprp VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsn1NBlock(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsn1NReticle(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnDrv1NDesign(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnDsn1NDevice(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	dsnNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnDsn1NDomain(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	dsnNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnDsn1NDomaingd(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	dsnNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnDsn1NStack(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	dsnNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnHk1NArcguide(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnHk1NLayer(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnHk1NLevel(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnHk1NLineguide(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnHk1NStructure(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnHk1NVertex(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	ixVDim INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refPlnrMProject BIGINT UNSIGNED,
	ixWModtype INT UNSIGNED,
	modRefPlnrMDesign BIGINT UNSIGNED,
	drvRefPlnrMDesign BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDsnMod1NDesign(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDtpAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	refPlnrMFile BIGINT UNSIGNED,
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDtpHk1NStructure(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDtpKParKey(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	sref VARCHAR(50),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDtpList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	supRefPlnrMDevice BIGINT UNSIGNED,
	ixVAligntype INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDtpSup1NDevice(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	supNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDtpTpl1NDevice(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDvcAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	x2SrefKKey VARCHAR(50),
	refPlnrMFile BIGINT UNSIGNED,
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDvcHk1NArcguide(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDvcHk1NLineguide(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDvcHk1NStructure(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDvcHk1NVertex(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDvcList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	dsnRefPlnrMDesign BIGINT UNSIGNED,
	supRefPlnrMDevice BIGINT UNSIGNED,
	tplRefPlnrMDevice BIGINT UNSIGNED,
	ixVModtype INT UNSIGNED,
	ixVAligntype INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQDvcSup1NDevice(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	supNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQFilList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Filename VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	srefKMimetype VARCHAR(50),
	Size INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQFilMNCalc(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMCalcitem BIGINT UNSIGNED,
	ixVIo INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQLyr1NBlock(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQLyr1NReticle(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQLyrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	x1RefPlnrMDesign BIGINT UNSIGNED,
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	refPlnrMMaterial BIGINT UNSIGNED,
	ixVTtype INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQLyrMNStructure(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQMat1NLayer(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQMatAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefPlnrMDesign BIGINT UNSIGNED,
	x2SrefKCat VARCHAR(50),
	x3SrefKProp VARCHAR(50),
	refPlnrMFile BIGINT UNSIGNED,
	Val VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQMatList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refPlnrMCalc BIGINT UNSIGNED,
	modRefPlnrMMaterial BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQMatMod1NMaterial(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQMatRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQPreselect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQPrj1NCalc(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQPrj1NDesign(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQPrjList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(50),
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQPrjMNTapeout(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQPrsADetail(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQPrsList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	Lastname VARCHAR(50),
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixVSex INT UNSIGNED,
	Tel VARCHAR(255),
	Eml VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQRtcList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	refPlnrMDesign BIGINT UNSIGNED,
	refPlnrMLayer BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQSelect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ix INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (ix)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQSru1NBlock(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQSruList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQSruMNLayer(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQSruMNStack(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	fromSrefPlnrMLayer VARCHAR(50),
	toSrefPlnrMLayer VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQSruSru1NFace(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQStkHk1NLayer(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQStkHk1NLevel(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQStkList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	dsnRefPlnrMDesign BIGINT UNSIGNED,
	ixVModtype INT UNSIGNED,
	ixVFlrAligntype INT UNSIGNED,
	ixVCeilAligntype INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQStkMNStructure(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	fromSrefPlnrMLayer VARCHAR(50),
	toSrefPlnrMLayer VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQTpo1NArray(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQTpoHk1NReticle(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQTpoList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	ixVState INT UNSIGNED,
	Hflip TINYINT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQTpoMNProject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQUsgAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxPlnrVCard INT UNSIGNED,
	ixPlnrWUiaccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQUsgList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQUsgMNUser(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixPlnrVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQUsr1NSession(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQUsrAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxPlnrVCard INT UNSIGNED,
	ixPlnrWUiaccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQUsrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refPlnrMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refPlnrMUsergroup BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixPlnrVLocale INT UNSIGNED,
	ixPlnrVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblPlnrQUsrMNUsergroup(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixPlnrVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

